// The dependency bundle every use case and service takes a Pick of.
import type { AccountRepo } from './account-repo';
import type { AccountTestRepo } from './account-test-repo';
import type { TransportResolver } from './agent-transport';
import type { AppSettingsRepo } from './app-settings-repo';
import type { BindingRepo } from './binding-repo';
import type { CapabilityCatalog } from './capability-catalog';
import type { CapabilityDiscovery } from './capability-discovery';
import type { CheckpointCommitter } from './checkpoints';
import type { Clock } from './clock';
import type { DefinitionStore } from './definition-store';
import type { EventLog } from './event-log';
import type { GitProbe } from './git-probe';
import type { IdGen } from './id-gen';
import type { InstructionFiles } from './instruction-files';
import type { DispatchStatusHolder, MachineProbe } from './machine-probe';
import type { ModelCatalog } from './model-catalog';
import type { Notifier } from './notifier';
import type { PageFiles } from './page-files';
import type { PageRepo } from './page-repo';
import type { PhaseAutoRunRepo } from './phase-auto-run-repo';
import type { ProjectRepo } from './project-repo';
import type { ProposalRepo } from './proposal-repo';
import type { QueueRepo } from './queue-repo';
import type { RepoFolders } from './repo-folders';
import type { RepoRegistry } from './repo-registry';
import type { RunDirs } from './run-dirs';
import type { RunRepo } from './run-repo';
import type { McpEndpoint, RunTokens } from './run-tokens';
import type { ScratchDirs } from './scratch-dirs';
import type { SecretVault } from './secret-vault';
import type { CommandRunner, EvidenceChecker, SecretScanner, Worktrees } from './repo-tools';
import type { WorkOrderRepo } from './work-order-repo';
import type { WorktreeFiles } from './worktree-files';

export interface AppDeps {
  readonly clock: Clock;
  readonly ids: IdGen;
  readonly log: EventLog;
  readonly workOrders: WorkOrderRepo;
  readonly runs: RunRepo;
  readonly accounts: AccountRepo;
  readonly capabilities: CapabilityCatalog;
  readonly capabilityDiscovery: CapabilityDiscovery;
  readonly modelCatalog: ModelCatalog;
  readonly projects: ProjectRepo;
  readonly repos: RepoRegistry;
  readonly bindings: BindingRepo;
  readonly queue: QueueRepo;
  readonly definitions: DefinitionStore;
  readonly proposals: ProposalRepo;
  readonly pages: PageRepo;
  readonly pageFiles: PageFiles;
  readonly secrets: SecretVault;
  readonly transports: TransportResolver;
  readonly commands: CommandRunner;
  readonly secretScanner: SecretScanner;
  readonly worktrees: Worktrees;
  readonly evidence: EvidenceChecker;
  readonly git: GitProbe;
  readonly notifier: Notifier;
  readonly instructionFiles: InstructionFiles;
  readonly checkpoints: CheckpointCommitter;
  readonly accountTests: AccountTestRepo;
  readonly settings: AppSettingsRepo;
  readonly phaseAutoRuns: PhaseAutoRunRepo;
  readonly scratch: ScratchDirs;
  readonly repoFolders: RepoFolders;
  readonly worktreeFiles: WorktreeFiles;
  readonly machine: MachineProbe;
  readonly dispatchStatus: DispatchStatusHolder;
  readonly runTokens: RunTokens;
  readonly runDirs: RunDirs;
  /** How Docket's own MCP child is launched; undefined when this shell runs none. */
  readonly mcpEndpoint: McpEndpoint | undefined;
}
