// labels/en.ts — English bundle. English is a peer locale, not a fallback: a key it misses falls
// back to Turkish in the resolver (U-9).
import type { LabelBundle } from './keys';

export const EN: LabelBundle = {
  'error.invalid_id': 'Invalid id.',
  'error.definitions_invalid': 'Definitions are invalid; the workspace definition could not be read.',
  'error.unknown_flow': 'Unknown flow.',
  'error.flow_not_enabled': 'This flow is not enabled in the workspace.',
  'error.unknown_task': 'Unknown task.',
  'error.empty_title': 'The title cannot be empty.',
  'error.not_found': 'The record was not found.',
  'error.already_done': 'The work order is already done.',
  'error.not_blocked': 'The work order is not blocked.',
  'error.not_ready': 'The stage cannot be started yet.',
  'error.unknown_role': 'Unknown role.',
  'error.no_binding': 'No account binding exists for this role.',
  'error.no_account': 'No account is available.',
  'error.not_current_stage': 'The gate does not belong to the current stage.',
  'error.not_pending': 'The gate is not pending.',
  'error.not_a_human_gate': 'This gate is not decided by a human.',
  'error.agent_cannot_decide': 'Only a human can make this decision.',
  'error.stale': 'The proposal is stale; refresh the change first.',
  'error.self_approval': 'You cannot approve your own proposal.',
  'error.invalid_after': 'The proposal’s valid-after time is invalid.',
  'error.binding_exists': 'The account is still referenced by a role binding; update the binding first.',
  'error.not_a_deploy_gate': 'This gate is not a deploy gate.',
  'error.no_approval': 'Only a user can approve a deployment.',
  'error.confirmation_mismatch': 'The typed environment confirmation does not match; type the environment name exactly.',
  'error.promote_prerequisite_missing': 'The same commit must be deployed successfully in the prerequisite environment first.',
  'error.unknown_environment': 'The environment is not among the definitions.',
  'error.no_repo': 'The repository worktree could not be prepared.',
  'error.unknown': 'An unexpected error occurred.',
  'attention.permission_ask': 'Permission ask',
  'attention.awaiting_human': 'Awaiting human',
  'attention.limit_waiting': 'Waiting on limit',
  'attention.blocked': 'Blocked',
  'validate.title_required': 'Enter a title.',
  'validate.flow_required': 'Choose a flow.',
  'gate.state.pending': 'Pending',
  'gate.state.passed': 'Passed',
  'gate.state.upcoming': 'Upcoming',
  'gate.deploy.protected': 'Protected environment',
  'gate.deploy.prerequisite': 'Promotion chain',
  'wo.status.ready': 'Ready',
  'wo.status.running': 'Running',
  'wo.status.gating': 'Evaluating',
  'wo.status.awaiting_human': 'Awaiting human',
  'wo.status.limit_waiting': 'Waiting on limit',
  'wo.status.blocked': 'Blocked',
  'wo.status.done': 'Done',
  'detail.section.stages': 'Stages and gates',
  'detail.section.runs': 'Runs',
  'detail.section.environments': 'Environments',
  'detail.section.asks': 'Permission asks',
  'detail.stage.current': 'Current stage',
  'detail.action.startStage': 'Start the stage',
  'detail.loading': 'Loading…',
  'detail.run.empty': 'No runs for this work order yet.',
  'detail.run.running': 'Running',
  'run.outcome.succeeded': 'Succeeded',
  'run.outcome.failed': 'Failed',
  'run.outcome.limit': 'Limit',
  'run.outcome.cancelled': 'Cancelled',
  'gate.kind.human': 'Human approval',
  'gate.kind.command': 'Command set',
  'gate.kind.agent_verdict': 'Agent verdict',
  'gate.kind.secret_scan': 'Secret scan',
  'gate.kind.page_approval': 'Page approval',
  'gate.kind.deploy': 'Deploy',
  'gate.kind.remote_checks': 'Remote checks',
  'action.approve': 'Approve',
  'action.reject': 'Reject',
  'action.allow': 'Allow',
  'action.deny': 'Deny',
  'detail.deploy.commitLabel': 'Commit',
  'detail.deploy.commitPlaceholder': 'commit id to deploy',
  'detail.deploy.confirmPrompt': 'Protected environment: type the environment name exactly to approve.',
  'detail.deploy.confirmPlaceholder': 'environment name',
  'detail.deploy.approve': 'Approve deploy',
  'detail.secretScan.pending': 'Scan waiting: the changes will be scanned locally against secret patterns.',
  'detail.secretScan.passed': 'Scan clean: no secret patterns found in the changes.',
  'live.title': 'Live stream',
  'live.empty': 'Waiting for events…',
  'live.ended': 'The stream has ended.',
  'live.ask.title': 'Permission ask',
  'live.kind.thought': 'Thought',
  'live.kind.message': 'Message',
  'live.kind.usage': 'Usage',
  'live.kind.quotaSignal': 'Quota signal',
  'live.tool.running': 'running',
  'live.tool.ok': 'ok',
  'live.tool.failed': 'failed',
  'live.usage.input': 'input',
  'live.usage.output': 'output',
  'live.usage.cached': 'cached',
  'live.usage.cost': 'cost',
  'live.meter.used': 'used',
  'live.meter.limit': 'limit',
  'success.workOrder.open': 'Work order opened.',
  'success.workOrder.block': 'Work order blocked.',
  'success.workOrder.unblock': 'Work order unblocked.',
  'success.workOrder.close': 'Work order closed.',
  'success.workOrder.enqueue': 'Stage queued.',
  'success.gate.decide': 'Gate decision recorded.',
  'success.proposal.decide': 'Proposal decision recorded.',
  'success.permission.answer': 'Permission answer recorded.',
  'success.deploy.approve': 'Deploy approved and executed.',
  'success.account.save': 'Account saved.',
  'success.account.remove': 'Account removed.',
  'success.binding.save': 'Role binding saved.',
};
