// labels/en.ts — English bundle. English is a peer locale, not a fallback: a key it misses falls
// back to Turkish in the resolver (U-9).
import type { LabelBundle } from './keys';

export const EN: LabelBundle = {
  'error.invalid_id': 'Invalid id.',
  'error.definitions_invalid': 'Definitions are invalid; the project definition could not be read.',
  'error.unknown_flow': 'Unknown flow.',
  'error.flow_not_enabled': 'This flow is not enabled in this repo.',
  'error.unknown_task': 'Unknown task.',
  'error.empty_title': 'The title cannot be empty.',
  'error.not_found': 'The record was not found.',
  'error.already_done': 'The work order is already done.',
  'error.not_blocked': 'The work order is not blocked.',
  'error.not_ready': 'The stage cannot be started yet.',
  'error.unknown_role': 'Unknown role.',
  'error.no_binding': 'No account binding exists for this role.',
  'error.no_account': 'No account is available.',
  'error.not_current_stage': 'The gate does not belong to the current stage.',
  'error.not_pending': 'The gate is not pending.',
  'error.not_a_human_gate': 'This gate is not decided by a human.',
  'error.agent_cannot_decide': 'Only a human can make this decision.',
  'error.stale': 'The proposal is stale; refresh the change first.',
  'error.self_approval': 'You cannot approve your own proposal.',
  'error.invalid_after': 'The proposal’s valid-after time is invalid.',
  'error.binding_exists': 'The account is still referenced by a role binding; update the binding first.',
  'error.not_a_deploy_gate': 'This gate is not a deploy gate.',
  'error.no_approval': 'Only a user can approve a deployment.',
  'error.confirmation_mismatch': 'The typed environment confirmation does not match; type the environment name exactly.',
  'error.promote_prerequisite_missing': 'The same commit must be deployed successfully in the prerequisite environment first.',
  'error.unknown_environment': 'The environment is not among the definitions.',
  'error.no_repo': 'The repository worktree could not be prepared.',
  'error.unknown': 'An unexpected error occurred.',
  'attention.permission_ask': 'Permission ask',
  'attention.awaiting_human': 'Awaiting human',
  'attention.limit_waiting': 'Waiting on limit',
  'attention.blocked': 'Blocked',
  'validate.title_required': 'Enter a title.',
  'validate.flow_required': 'Choose a flow.',
  'gate.state.pending': 'Pending',
  'gate.state.passed': 'Passed',
  'gate.state.upcoming': 'Upcoming',
  'gate.deploy.protected': 'Protected environment',
  'gate.deploy.prerequisite': 'Promotion chain',
  'wo.status.ready': 'Ready',
  'wo.status.running': 'Running',
  'wo.status.gating': 'Evaluating',
  'wo.status.awaiting_human': 'Awaiting human',
  'wo.status.limit_waiting': 'Waiting on limit',
  'wo.status.blocked': 'Blocked',
  'wo.status.done': 'Done',
  'detail.section.stages': 'Stages and gates',
  'detail.section.runs': 'Runs',
  'detail.section.environments': 'Environments',
  'detail.section.asks': 'Permission asks',
  'detail.stage.current': 'Current stage',
  'detail.action.startStage': 'Start the stage',
  'detail.loading': 'Loading…',
  'detail.run.empty': 'No runs for this work order yet.',
  'detail.run.running': 'Running',
  'run.outcome.succeeded': 'Succeeded',
  'run.outcome.failed': 'Failed',
  'run.outcome.limit': 'Limit',
  'run.outcome.cancelled': 'Cancelled',
  'gate.kind.human': 'Human approval',
  'gate.kind.command': 'Command set',
  'gate.kind.agent_verdict': 'Agent verdict',
  'gate.kind.secret_scan': 'Secret scan',
  'gate.kind.page_approval': 'Page approval',
  'gate.kind.deploy': 'Deploy',
  'gate.kind.remote_checks': 'Remote checks',
  'action.approve': 'Approve',
  'action.reject': 'Reject',
  'action.allow': 'Allow',
  'action.deny': 'Deny',
  'detail.deploy.commitLabel': 'Commit',
  'detail.deploy.commitPlaceholder': 'commit id to deploy',
  'detail.deploy.confirmPrompt': 'Protected environment: type the environment name exactly to approve.',
  'detail.deploy.confirmPlaceholder': 'environment name',
  'detail.deploy.approve': 'Approve deploy',
  'detail.secretScan.pending': 'Scan waiting: the changes will be scanned locally against secret patterns.',
  'detail.secretScan.passed': 'Scan clean: no secret patterns found in the changes.',
  'live.title': 'Live stream',
  'live.empty': 'Waiting for events…',
  'live.ended': 'The stream has ended.',
  'live.ask.title': 'Permission ask',
  'live.kind.thought': 'Thought',
  'live.kind.message': 'Message',
  'live.kind.usage': 'Usage',
  'live.kind.quotaSignal': 'Quota signal',
  'live.tool.running': 'running',
  'live.tool.ok': 'ok',
  'live.tool.failed': 'failed',
  'live.usage.input': 'input',
  'live.usage.output': 'output',
  'live.usage.cached': 'cached',
  'live.usage.cost': 'cost',
  'live.meter.used': 'used',
  'live.meter.limit': 'limit',
  'shell.title': 'Docket',
  'nav.cockpit': 'Cockpit',
  'nav.workspaces': 'Repos',
  'nav.workspaces.empty': 'No repos yet.',
  'cockpit.section.attention': 'Waiting on you',
  'cockpit.section.running': 'Running',
  'cockpit.attention.empty': 'Nothing is waiting on you right now.',
  'cockpit.running.empty': 'Nothing is running right now.',
  'cockpit.loading': 'Loading…',
  'board.loading': 'Loading…',
  'board.section.done': 'Done',
  'board.create.title': 'New work order',
  'board.create.titleLabel': 'Title',
  'board.create.titlePlaceholder': 'work order title',
  'board.create.flowLabel': 'Flow',
  'board.create.flowPlaceholder': 'flow',
  'board.create.submit': 'Open',
  'action.retry': 'Retry',
  'action.open': 'Open',
  'success.workOrder.open': 'Work order opened.',
  'success.workOrder.block': 'Work order blocked.',
  'success.workOrder.unblock': 'Work order unblocked.',
  'success.workOrder.close': 'Work order closed.',
  'success.workOrder.enqueue': 'Stage queued.',
  'success.task.open': 'Task work orders opened.',
  'success.project.attach': 'Project attached.',
  'success.repo.register': 'Repo registered.',
  'success.repo.unregister': 'Repo unregistered.',
  'success.gate.decide': 'Gate decision recorded.',
  'success.proposal.decide': 'Proposal decision recorded.',
  'success.permission.answer': 'Permission answer recorded.',
  'success.deploy.approve': 'Deploy approved and executed.',
  'nav.settings': 'Settings',
  'settings.section.accounts': 'Accounts',
  'settings.section.bindings': 'Role bindings',
  'settings.section.discovery': 'Provider discovery',
  'settings.accounts.empty': 'No accounts yet.',
  'settings.meters.empty': 'No meters for this account.',
  'settings.meter.remaining': 'remaining',
  'settings.meter.resetsAt': 'resets at',
  'settings.account.remove': 'Remove account',
  'settings.remove.warning': 'This account is still used by these role bindings:',
  'settings.remove.confirm': 'Remove anyway',
  'settings.remove.cancel': 'Cancel',
  'settings.binding.edit': 'Edit',
  'settings.binding.save': 'Save',
  'settings.binding.cancel': 'Cancel',
  'settings.binding.add': 'New binding',
  'settings.binding.empty': 'No role bindings yet.',
  'settings.binding.role': 'Role',
  'settings.binding.rolePlaceholder': 'role (slug)',
  'settings.binding.model': 'model',
  'settings.binding.scope.global': 'Whole machine',
  'settings.binding.scope.workspace': 'Repo',
  'settings.binding.scope.project': 'Project',
  'settings.binding.scope.workOrder': 'Work order',
  'settings.discovery.refresh': 'Discover',
  'settings.discovery.running': 'Discovery is running…',
  'settings.discovery.failed': 'Discovery failed.',
  'settings.discovery.empty': 'No discovery results yet.',
  'settings.discovery.flags': 'flags',
  'settings.language.label': 'Language',
  'settings.language.tr': 'Türkçe',
  'settings.language.en': 'English',
  'source.pushed': 'pushed',
  'source.polled': 'polled',
  'source.header': 'header',
  'source.captured_from_error': 'captured from error',
  'source.estimated': 'estimated',
  'source.documented_rule': 'documented rule',
  'source.unknown': 'unknown',
  'auth.mode.subscription': 'Subscription',
  'auth.mode.api_key': 'API key',
  'auth.mode.cloud': 'Cloud',
  'auth.mode.byok': 'Own key',
  'wizard.title': 'Setup',
  'wizard.checking': 'Checking…',
  'wizard.step.source': 'Definitions source',
  'wizard.step.account': 'Account',
  'wizard.step.binding': 'Role binding',
  'wizard.step.done': 'Done',
  'wizard.back': 'Back',
  'wizard.next': 'Next',
  'wizard.hint.source': 'Verify the definitions source to continue.',
  'wizard.hint.account': 'Choose an installed and logged-in provider to continue.',
  'wizard.hint.binding': 'Bind at least one role to continue.',
  'wizard.source.label': 'Definitions source',
  'wizard.source.placeholder': 'repo (slug)',
  'wizard.source.check': 'Verify source',
  'wizard.source.probing': 'Verifying…',
  'wizard.source.ok': 'The source is readable.',
  'wizard.source.failed': 'The source could not be read.',
  'wizard.account.title': 'Discovered providers',
  'wizard.account.refresh': 'Scan again',
  'wizard.account.empty': 'No installed provider found.',
  'wizard.account.selected': 'Selected',
  'wizard.account.label': 'Account label',
  'wizard.account.labelPlaceholder': 'account label',
  'wizard.account.authMode': 'Authentication',
  'wizard.account.plan': 'Plan (optional)',
  'wizard.account.planPlaceholder': 'plan',
  'wizard.binding.role': 'Role',
  'wizard.binding.rolePlaceholder': 'role (slug)',
  'wizard.binding.bind': 'Bind role',
  'wizard.binding.bound': 'Bound roles',
  'wizard.binding.empty': 'No role bound yet.',
  'discovery.found': 'found',
  'discovery.missing': 'not found',
  'discovery.loggedIn': 'logged in',
  'discovery.loginRequired': 'login required',
  'discovery.loginUnknown': 'login state unknown',
  'errorBoundary.title': 'The app hit an unexpected error.',
  'errorBoundary.reload': 'Reload',
  'success.account.save': 'Account saved.',
  'success.account.remove': 'Account removed.',
  'success.binding.save': 'Role binding saved.',
};
