// labels/keys.ts — the closed set of user-visible copy keys (U-1). Every string a component or
// store renders goes through one of these keys; a literal user-visible string outside a bundle is
// a defect (codes, ids and slugs excluded). Initial key set: every failure code the current api
// can return (docs/v2/application.md § 4), the generic failure key, the attention kinds, and one
// success confirmation per command.
export const LABEL_KEYS = [
  // Failure codes — commands and queries report failure the same way (api/api.ts).
  'error.invalid_id',
  'error.definitions_invalid',
  'error.unknown_flow',
  'error.flow_not_enabled',
  'error.unknown_task',
  'error.empty_title',
  'error.not_found',
  'error.already_done',
  'error.not_blocked',
  'error.not_ready',
  'error.unknown_role',
  'error.no_binding',
  'error.no_account',
  'error.not_current_stage',
  'error.not_pending',
  'error.not_a_human_gate',
  'error.agent_cannot_decide',
  'error.stale',
  'error.self_approval',
  'error.invalid_after',
  'error.binding_exists',
  // Spend-consent refusals (application use-cases/spend-consent.ts, P-40).
  'error.invalid_model',
  'error.invalid_cap',
  // Deploy-gate errors (application deploy-gate.ts; confirmation_mismatch also reports the
  // detail store's E-8 refusal, U-4).
  'error.not_a_deploy_gate',
  'error.no_approval',
  'error.confirmation_mismatch',
  'error.promote_prerequisite_missing',
  'error.unknown_environment',
  'error.no_repo',
  // Generic failure for an unknown code (U-8).
  'error.unknown',
  // Attention kinds (api/queries.ts AttentionItem).
  'attention.permission_ask',
  'attention.awaiting_human',
  'attention.limit_waiting',
  'attention.blocked',
  // Store-side create-intent validation reasons (U-3, stores/board.ts).
  'validate.title_required',
  'validate.flow_required',
  // Gate states on the work-order detail (U-4, stores/work-order-detail.ts).
  'gate.state.pending',
  'gate.state.passed',
  'gate.state.upcoming',
  // Deploy-gate copy (U-4): protection marker and the read-only promotion chain (E-5).
  'gate.deploy.protected',
  'gate.deploy.prerequisite',
  // Work-order statuses on the detail header (screens/detail.tsx).
  'wo.status.ready',
  'wo.status.running',
  'wo.status.gating',
  'wo.status.awaiting_human',
  'wo.status.limit_waiting',
  'wo.status.blocked',
  'wo.status.done',
  // The work-order code prefix of the locale (U-22): TR İE-, EN WO-.
  'workOrder.codePrefix',
  // Detail screen: sections, stage marker, loading and the run list.
  'detail.section.stages',
  'detail.section.runs',
  'detail.section.environments',
  'detail.section.asks',
  'detail.stage.current',
  'detail.action.startStage',
  'detail.loading',
  'detail.run.empty',
  'detail.run.running',
  // Detail screen, U-19: the in-place back row, the flow strip's gate chip, and the expected-of-
  // you section's card and outcomes.
  'detail.back.board',
  'detail.back.cockpit',
  'detail.back.account',
  'detail.back.roadmap',
  'detail.flow.gate',
  'detail.section.expected',
  'detail.expected.empty',
  'detail.expected.done',
  'detail.expected.body',
  'detail.expected.approve',
  'detail.expected.refuse',
  'success.gate.approved',
  'success.gate.rejected',
  'run.outcome.succeeded',
  'run.outcome.failed',
  'run.outcome.limit',
  'run.outcome.cancelled',
  // Gate kind names (the detail's gate rows).
  'gate.kind.human',
  'gate.kind.command',
  'gate.kind.agent_verdict',
  'gate.kind.secret_scan',
  'gate.kind.page_approval',
  'gate.kind.deploy',
  'gate.kind.remote_checks',
  // Decisions the screens offer.
  'action.approve',
  'action.reject',
  'action.allow',
  'action.deny',
  // Deploy approval flow (E-8 mirrored at the screen: typed confirmation).
  'detail.deploy.commitLabel',
  'detail.deploy.commitPlaceholder',
  'detail.deploy.confirmPrompt',
  'detail.deploy.confirmPlaceholder',
  'detail.deploy.approve',
  // Secret-scan evidence copy (what the scan did / will do).
  'detail.secretScan.pending',
  'detail.secretScan.passed',
  // Live pane (U-5): title, states, item kinds, tool statuses, usage and meter fields.
  'live.title',
  'live.empty',
  'live.ended',
  'live.ask.title',
  'live.kind.thought',
  'live.kind.message',
  'live.kind.usage',
  'live.kind.quotaSignal',
  'live.tool.running',
  'live.tool.ok',
  'live.tool.failed',
  'live.usage.input',
  'live.usage.output',
  'live.usage.cached',
  'live.usage.cost',
  'live.meter.used',
  'live.meter.limit',
  // Screens A: the shell's nav landmark, the title bar's update button, the sidebar's nav rows,
  // the centered search palette, the project tree and the accounts frame (screens/shell.tsx,
  // components/title-bar.tsx, components/sidebar-nav.tsx, components/search-palette.tsx,
  // components/sidebar-tree.tsx, components/sidebar-accounts.tsx).
  'shell.nav',
  'shell.nav.back',
  'shell.nav.forward',
  'shell.wordmark',
  'shell.search',
  'nav.home',
  'nav.cockpit',
  'nav.search',
  'nav.search.kbd',
  'nav.phone',
  'palette.title',
  'palette.kbd.esc',
  'palette.placeholder',
  'palette.empty',
  'palette.kind.project',
  'palette.kind.repo',
  // The palette's history standing (an empty query with remembered searches): the header, its
  // clear control and the per-row remove control's accessible name.
  'palette.history.title',
  'palette.history.clear',
  'palette.history.remove',
  'nav.projects',
  'nav.projects.empty',
  'nav.projects.sort',
  'nav.projects.new',
  'tree.open',
  'accounts.title',
  'accounts.refresh',
  'accounts.toggle',
  'accounts.empty',
  'account.window.five_hour',
  'account.window.week',
  'account.window.month',
  // Account view (U-20): the windows' blocks, the active-work rows, the limit-behaviour band.
  'account.back',
  'account.loading',
  'account.section.windows',
  'account.window.resets',
  'account.window.remaining',
  'account.window.info',
  'account.plan.subscription',
  'account.section.work',
  'account.work.empty',
  'account.policy.when',
  'account.policy.info',
  'account.policy.subject',
  'info.trigger.prefix',
  'account.policy.wait_resume',
  'account.policy.switch_pool',
  'account.policy.fallback_account',
  'account.policy.ask',
  'account.edit',
  // Roadmap screen: title, caption, loading and problem states, task row and expansion
  // (screens/roadmap.tsx).
  'roadmap.title',
  'roadmap.caption',
  'roadmap.loading',
  'roadmap.task.repoMany',
  'roadmap.task.noWorkOrders',
  'roadmap.task.openRepoBoard',
  'roadmap.task.done',
  'roadmap.task.current',
  'roadmap.task.remaining',
  // Cockpit screen: section titles, empty and loading states (screens/cockpit.tsx).
  'cockpit.section.attention',
  'cockpit.section.running',
  'cockpit.section.projects',
  'cockpit.section.closed',
  'cockpit.attention.empty',
  'cockpit.running.empty',
  'cockpit.projects.empty',
  'cockpit.closed.empty',
  'cockpit.loading',
  // Cockpit screen, U-21: the head's counts, the permission-ask row's question, the project
  // cards' counts and the closed rows' suffix.
  'cockpit.head.waiting',
  'cockpit.head.running',
  'cockpit.card.active',
  'cockpit.card.waiting',
  'cockpit.head.blocked',
  'cockpit.head.ok',
  'cockpit.head.idle',
  'cockpit.attention.hint',
  'cockpit.running.hint',
  'cockpit.closed.hint',
  'cockpit.ask.wants',
  'cockpit.head.queued',
  'cockpit.queued.queue',
  'cockpit.queued.limit',
  'cockpit.queued.limitAt',
  'cockpit.closed.merged',
  'cockpit.closed.cancelled',
  'cockpit.card.lastActivity',
  'cockpit.more',
  'cockpit.less',
  'cockpit.card.repos',
  'cockpit.card.singleRepo',
  'cockpit.card.toRoadmap',
  'cockpit.card.toBoard',
  'cockpit.error.title',
  'cockpit.error.empty',
  'cockpit.error.stale',
  'cockpit.error.unavailable',
  'cockpit.first.title',
  'cockpit.first.body',
  'cockpit.first.step1',
  'cockpit.first.step2',
  'cockpit.first.step3',
  // Board screen: loading, done lane and the create-work-order form (screens/board.tsx).
  'board.loading',
  'board.create.title',
  'board.create.titleLabel',
  'board.create.titlePlaceholder',
  'board.create.flowLabel',
  'board.create.flowPlaceholder',
  'board.create.submit',
  // Board screen, U-18: the view segment, the header's rule and shortcuts, the Kanban grammar
  // and the list view's rail.
  'board.view.aria',
  'board.view.kanban',
  'board.view.liste',
  'board.roadmap',
  'board.roadmap.title',
  'board.editProject',
  'board.editProject.title',
  'board.new',
  'board.done.jobs',
  'board.empty.stage',
  'board.list.col.code',
  'board.list.col.title',
  'board.list.col.status',
  'board.list.empty',
  'board.list.running',
  'board.list.waiting',
  // Kanban columns: the shut/open control, the pinned-open reason and the done column's name.
  'board.column.collapse',
  'board.column.expand',
  'board.column.locked',
  'board.column.shut',
  'board.column.done',
  // Decisions the screens offer.
  'action.retry',
  'action.open',
  // Settings screen (U-6): sections, account and meter rows, bindings editor, discovery list.
  'nav.settings',
  'settings.close',
  'settings.section.accounts',
  'settings.section.bindings',
  'settings.section.discovery',
  'settings.accounts.empty',
  'settings.meters.empty',
  'settings.meter.remaining',
  'settings.meter.resetsAt',
  'meter.value.percent',
  'meter.value.unit',
  'meter.unit.credits',
  'meter.unit.tokens',
  'meter.unit.requests',
  'meter.unit.prompts',
  'meter.unit.minutes',
  'settings.account.remove',
  'settings.remove.warning',
  'settings.remove.confirm',
  'settings.remove.cancel',
  'settings.binding.edit',
  'settings.binding.save',
  'settings.binding.cancel',
  'settings.binding.add',
  'settings.binding.empty',
  'settings.binding.role',
  'settings.binding.rolePlaceholder',
  'settings.binding.model',
  'settings.binding.scope.global',
  'settings.binding.scope.workspace',
  'settings.binding.scope.project',
  'settings.binding.scope.workOrder',
  'settings.discovery.refresh',
  'settings.discovery.running',
  'settings.discovery.failed',
  'settings.discovery.empty',
  'settings.discovery.flags',
  // Settings panel, accounts section — the per-account model list and the spend-consent flow
  // (P-40): billing marks, the stale note, the consent draft and its cap controls.
  'settings.models.toggle',
  'settings.models.default',
  'settings.models.empty',
  'settings.models.stale',
  'settings.models.refresh',
  'settings.models.metered',
  'settings.models.unknown',
  'settings.models.allowed',
  'settings.models.revoke',
  'settings.models.select',
  'settings.models.consent.title',
  'settings.models.consent.body',
  'settings.models.consent.scope',
  'settings.models.consent.amount',
  'settings.models.consent.amountPlaceholder',
  'settings.models.consent.amountHint',
  'settings.models.consent.allow',
  'settings.models.consent.cancel',
  // The spend cap's account scopes (the record's closed set) and the model tiers' chip names.
  'cap.scope.account_day',
  'cap.scope.account_week',
  'cap.scope.account_month',
  'tier.strong',
  'tier.balanced',
  'tier.fast',
  // Settings screen (U-24): the phone section's honest "not linked yet" standing, and the
  // Güncelleme section's version line, status lines and check action.
  'settings.section.phone',
  'settings.phone.none',
  'settings.phone.explain',
  'settings.phone.pair',
  'settings.phone.soon',
  'settings.section.update',
  'settings.update.version',
  'settings.update.status.none',
  'settings.update.status.available',
  'settings.update.status.downloading',
  'settings.update.status.ready',
  'settings.update.status.error',
  'settings.update.check',
  'update.error.offline',
  'update.error.failed',
  // The title bar's Update button (U-24): the apply and restart labels; the percent standing
  // renders the number, and its tooltip reuses the downloading status line.
  'update.button.now',
  'update.button.restart',
  // Language switcher (U-9): the control's own name and the languages' names — the names stay
  // native endonyms in both bundles, never translated.
  'settings.language.label',
  'settings.language.tr',
  'settings.language.en',
  // Meter observation sources (U-6; the closed ObservationSource set of the domain).
  'source.pushed',
  'source.polled',
  'source.header',
  'source.captured_from_error',
  'source.estimated',
  'source.documented_rule',
  'source.unknown',
  // Account auth modes (the record's closed set).
  'auth.mode.subscription',
  'auth.mode.api_key',
  'auth.mode.cloud',
  'auth.mode.byok',
  // Wizard screen (U-7): the first-run machine's steps, controls and gate-reason lines.
  'wizard.title',
  'wizard.checking',
  'wizard.step.source',
  'wizard.step.account',
  'wizard.step.binding',
  'wizard.step.done',
  'wizard.back',
  'wizard.next',
  'wizard.hint.source',
  'wizard.hint.account',
  'wizard.hint.binding',
  'wizard.source.label',
  'wizard.source.placeholder',
  'wizard.source.check',
  'wizard.source.probing',
  'wizard.source.ok',
  'wizard.source.failed',
  'wizard.account.title',
  'wizard.account.refresh',
  'wizard.account.empty',
  'wizard.account.selected',
  'wizard.account.label',
  'wizard.account.labelPlaceholder',
  'wizard.account.authMode',
  'wizard.account.plan',
  'wizard.account.planPlaceholder',
  'wizard.binding.role',
  'wizard.binding.rolePlaceholder',
  'wizard.binding.bind',
  'wizard.binding.bound',
  'wizard.binding.empty',
  // Discovery badges shared by the settings and wizard screens.
  'discovery.found',
  'discovery.missing',
  'discovery.loggedIn',
  'discovery.loginRequired',
  'discovery.loginUnknown',
  // Renderer error boundary: the root crash screen's title and its one recovery action.
  'errorBoundary.title',
  'errorBoundary.reload',
  // Success confirmations, one per command type (U-8).
  'success.workOrder.open',
  'success.workOrder.block',
  'success.workOrder.unblock',
  'success.workOrder.close',
  'success.workOrder.enqueue',
  'success.task.open',
  'success.project.attach',
  'success.repo.register',
  'success.repo.unregister',
  'success.gate.decide',
  'success.proposal.decide',
  'success.permission.answer',
  'success.deploy.approve',
  'success.account.save',
  'success.account.adopt',
  'success.account.remove',
  'success.account.consent.grant',
  'success.account.consent.revoke',
  'success.binding.save',
  'success.app.update.check',
  'success.app.update.apply',
] as const;

export type LabelKey = (typeof LABEL_KEYS)[number];

export type LabelBundle = Readonly<Record<LabelKey, string>>;
