// labels/tr.ts — Turkish bundle. Turkish is the default locale; every key of keys.ts carries copy.
import type { LabelBundle } from './keys';

export const TR: LabelBundle = {
  'error.invalid_id': 'Geçersiz kimlik.',
  'error.definitions_invalid': 'Tanımlar geçersiz; proje tanımı okunamadı.',
  'error.unknown_flow': 'Bilinmeyen akış.',
  'error.flow_not_enabled': 'Bu akış bu repoda etkin değil.',
  'error.unknown_task': 'Bilinmeyen görev.',
  'error.empty_title': 'Başlık boş olamaz.',
  'error.not_found': 'Kayıt bulunamadı.',
  'error.already_done': 'İş emri zaten tamamlandı.',
  'error.not_blocked': 'İş emri engellenmiş durumda değil.',
  'error.not_ready': 'Aşama henüz başlatılamaz.',
  'error.unknown_role': 'Bilinmeyen rol.',
  'error.no_binding': 'Bu rol için hesap bağlantısı yok.',
  'error.no_account': 'Kullanılabilir hesap yok.',
  'error.not_current_stage': 'Kapı geçerli aşamanın kapısı değil.',
  'error.not_pending': 'Kapı onay bekliyor durumda değil.',
  'error.not_a_human_gate': 'Bu kapı insan kararıyla açılmaz.',
  'error.not_a_changes_gate': 'Bu kapı bir değişiklik kapısı değil.',
  'error.agent_cannot_decide': 'Bu kararı yalnızca insan verebilir.',
  'error.stale': 'Teklif güncel değil; önce değişikliği yenileyin.',
  'error.self_approval': 'Kendi teklifinizi onaylayamazsınız.',
  'error.invalid_after': 'Teklifin geçerlilik zamanı geçersiz.',
  'error.binding_exists': 'Hesap bir rol bağlantısında kullanılıyor; önce bağlantıyı güncelleyin.',
  'error.invalid_model': 'Model geçersiz.',
  'error.invalid_cap': 'Harcama üst sınırı geçersiz.',
  'error.cap_required': 'Bir model onaylıyken son harcama üst sınırı kaldırılamaz; önce onayı geri çekin.',
  'error.not_a_deploy_gate': 'Bu kapı bir dağıtım kapısı değil.',
  'error.no_approval': 'Dağıtımı yalnızca kullanıcı onaylayabilir.',
  'error.confirmation_mismatch': 'Ortam adı doğrulaması eşleşmiyor; ortam adını aynen yazın.',
  'error.promote_prerequisite_missing': 'Aynı işlenen önce önceki ortamda başarıyla dağıtılmalı.',
  'error.unknown_environment': 'Ortam tanımları arasında bulunamadı.',
  'error.no_repo': 'Depo çalışma kopyası hazırlanamadı.',
  'error.not_a_repo': 'Bu klasör bir git deposu değil.',
  'error.no_project_yaml': 'Bu klasörde Docket proje dosyası (.docket/project.yaml) yok.',
  'error.repo_not_in_project': 'Proje dosyası bu depoyu listelemiyor.',
  'error.invalid_name': 'Proje adı boş olamaz ve en çok 80 karakter olabilir.',
  'error.not_a_folder': 'Bu yol bir klasör değil.',
  'error.folder_exists': 'Bu konumda aynı adlı bir klasör zaten var.',
  'error.docket_folder_exists': 'Bu klasörde yarım bir .docket var; elle düzelt.',
  'error.io_failed': 'Klasöre yazılamadı.',
  'error.project_exists': 'Bu klasör zaten bir Docket projesi.',
  'error.unknown': 'Beklenmeyen bir hata oluştu.',
  'attention.permission_ask': 'İzin bekleniyor',
  'attention.awaiting_human': 'İnsan yanıtı bekleniyor',
  'attention.limit_waiting': 'Limit bekleniyor',
  'attention.blocked': 'Engellendi',
  'validate.title_required': 'Bir başlık yazın.',
  'validate.flow_required': 'Bir akış seçin.',
  'gate.state.pending': 'Bekliyor',
  'gate.state.passed': 'Geçti',
  'gate.state.upcoming': 'Sırada',
  'gate.deploy.protected': 'Korumalı ortam',
  'gate.deploy.prerequisite': 'Yükseltme zinciri',
  'wo.status.ready': 'Hazır',
  'wo.status.running': 'Koşuyor',
  'wo.status.gating': 'Değerlendiriliyor',
  'wo.status.awaiting_human': 'İnsan yanıtı bekleniyor',
  'wo.status.limit_waiting': 'Limit bekleniyor',
  'wo.status.blocked': 'Engellendi',
  'wo.status.done': 'Tamamlandı',
  'workOrder.codePrefix': 'İE-',
  'detail.section.stages': 'Aşamalar ve kapılar',
  'detail.section.runs': 'Koşular',
  'detail.section.environments': 'Ortamlar',
  'detail.section.asks': 'İzin soruları',
  'detail.stage.current': 'Şu anki aşama',
  'detail.action.startStage': 'Aşamayı başlat',
  'detail.loading': 'Yükleniyor…',
  'detail.run.empty': 'Bu iş emrinde henüz koşu yok.',
  'detail.run.running': 'Koşuyor',
  'detail.back.board': '‹ Geri · pano',
  'detail.back.cockpit': '‹ Geri · kokpit',
  'detail.back.account': '‹ Geri · hesap',
  'detail.back.roadmap': '‹ Geri · yol haritası',
  'detail.flow.gate': 'kapı',
  'detail.section.expected': 'Bu aşamada senden beklenen',
  'detail.expected.empty': 'Bu aşamada senden beklenen bir şey yok.',
  'detail.expected.done': 'İş emri tamamlandı; beklenen bir şey yok.',
  'detail.expected.body': 'Onaylarsan iş emri bir sonraki aşamaya geçer; "Sorun var" dersen bu aşamada kalır.',
  'detail.expected.approve': 'Onayla ve ilerle',
  'detail.expected.refuse': 'Sorun var',
  'detail.expected.files': 'Değişen Dosyalar',
  'detail.expected.files.truncated': '…ve daha fazlası',
  'detail.expected.file.loading': 'Yükleniyor…',
  'detail.expected.file.error': 'Dosya okunamadı.',
  'detail.expected.file.truncated': '…dosyanın kalanı kesildi',
  'success.gate.approved': 'Onaylandı.',
  'success.gate.attestNoChange': 'Beyan kaydedildi: değişiklik gerekmiyordu.',
  'success.gate.attestRerun': 'Beyan kaydedildi: aşama yeniden çalışacak.',
  'success.gate.rejected': 'Reddedildi.',
  'run.outcome.succeeded': 'Başarılı',
  'run.outcome.failed': 'Başarısız',
  'run.outcome.limit': 'Limit',
  'run.outcome.cancelled': 'İptal edildi',
  'gate.kind.human': 'İnsan onayı',
  'gate.kind.command': 'Komut takımı',
  'gate.kind.changes': 'Değişiklik',
  'gate.kind.agent_verdict': 'Ajan kararı',
  'gate.kind.secret_scan': 'Sır taraması',
  'gate.kind.page_approval': 'Sayfa onayı',
  'gate.kind.deploy': 'Dağıtım',
  'gate.kind.remote_checks': 'Uzak kontroller',
  'action.approve': 'Onayla',
  'action.reject': 'Reddet',
  'action.allow': 'İzin ver',
  'action.deny': 'Reddet',
  'detail.deploy.commitLabel': 'İşlenen (commit)',
  'detail.deploy.commitPlaceholder': 'dağıtılacak işlenen kimliği',
  'detail.deploy.confirmPrompt': 'Korumalı ortam: onaylamak için ortam adını aynen yazın.',
  'detail.deploy.confirmPlaceholder': 'ortam adı',
  'detail.deploy.approve': 'Dağıtımı onayla',
  'detail.secretScan.pending': 'Tarama bekliyor: değişiklikler yerelde sır desenlerine karşı taranacak.',
  'detail.changes.attestNoChange': 'Değişiklik gerekmiyordu',
  'detail.changes.attestRerun': 'Eksik, yeniden çalıştır',
  'detail.secretScan.passed': 'Tarama bulgu vermedi: değişikliklerde sır deseni bulunamadı.',
  'live.title': 'Canlı akış',
  'live.empty': 'Olay bekleniyor…',
  'live.ended': 'Akış bitti.',
  'live.ask.title': 'İzin sorusu',
  'live.kind.thought': 'Düşünce',
  'live.kind.message': 'İleti',
  'live.kind.usage': 'Kullanım',
  'live.kind.quotaSignal': 'Kota sinyali',
  'live.tool.running': 'çalışıyor',
  'live.tool.ok': 'tamam',
  'live.tool.failed': 'başarısız',
  'live.usage.input': 'girdi',
  'live.usage.output': 'çıktı',
  'live.usage.cached': 'önbellek',
  'live.usage.cost': 'maliyet',
  'live.meter.used': 'kullanılan',
  'live.meter.limit': 'limit',
  'shell.nav': 'Gezinme',
  'shell.nav.back': 'Geri ⌘[',
  'shell.nav.forward': 'İleri ⌘]',
  'shell.wordmark': 'Docket',
  'shell.search': 'Ara ⌘K',
  'nav.home': 'Anasayfa',
  'nav.cockpit': 'Kokpit',
  'nav.search': 'Ara',
  'nav.search.kbd': '⌘K',
  'nav.library': 'Artifact\'lar',
  'nav.phone': 'Telefon',
  'palette.title': 'Ara',
  'palette.kbd.esc': 'Esc',
  'palette.placeholder': 'Proje veya repo ara…',
  'palette.empty': 'Sonuç yok.',
  'palette.kind.project': 'proje',
  'palette.kind.repo': 'repo',
  'palette.history.title': 'Son aramalar',
  'palette.history.clear': 'Temizle',
  'palette.history.remove': 'Aramayı geçmişten kaldır',
  'nav.projects': 'Projeler',
  'nav.projects.empty': 'Projelerin burada görünecek.',
  'nav.projects.sort': 'Projeleri sırala',
  'nav.projects.new': 'Yeni proje',
  'tree.open': 'Projeyi aç/kapa',
  'accounts.title': 'Hesaplar',
  'accounts.refresh': 'Kullanımı yenile',
  'accounts.toggle': 'Hesapları gizle / göster',
  'accounts.empty': 'Henüz hesap yok.',
  'accounts.reserved': "rezervde",
  'accounts.unadded': "{n} hesap eklenmedi",
  'accounts.unadded.one': "{n} hesap eklenmedi",
  'accounts.unadded.see': "Gör ›",
  'accounts.barHint': "Çubuk en dar limiti gösterir.",
  'accounts.noLimit': "Limit bilgisi yok",
  'accounts.tightest': "En dar",
  'accounts.limits': "Limitler",
  'accounts.open': "Hesabı aç",
  'account.back': '‹ Geri · kokpit',
  'account.loading': 'Yükleniyor…',
  'account.section.windows': 'Pencereler',
  'account.window.info': 'Bu pencere, hesabın sağlayıcısının bildirdiği kullanımı izler; süre dolunca sıfırlanır.',
  'account.plan.subscription': 'Abonelik ✓',
  'account.section.work': 'Bu hesabı kullanan aktif işler',
  'account.work.empty': 'Bu hesapla koşan aktif iş yok.',
  'account.policy.info': "Limit dolduğunda bu hesabın işleri ne yapar",
  'account.policy.subject': 'limit davranışı',
  'info.trigger.prefix': 'Bilgi: ',
  'account.policy.wait_resume': 'Sıfırlanınca sürdür',
  'account.policy.switch_pool': 'Başka havuza geç',
  'account.policy.fallback_account': 'Yedek hesaba geç',
  'account.policy.ask': 'Bana sor',
  'account.edit': "Ayarlar'da düzenle ↗",
  'account.band.sentence': "Limit dolunca: {policy} · Rezerv: {reserve}",
  'account.band.reserve.none': "Yok",
  'account.band.reserve.one': "%{value}",
  'account.band.reserve.two': "kısa %{short} · uzun %{long}",
  'roadmap.title': 'Yol haritası',
  'roadmap.caption': 'Yol haritası projenin ana deposunda (★) durur. Birden çok repoya dağılan görevi açınca her reponun iş emrini görürsün.',
  'roadmap.loading': 'Yükleniyor…',
  'roadmap.task.repoMany': 'repo',
  'roadmap.task.noWorkOrders': 'Bu görevin bağlı iş emri yok.',
  'roadmap.task.openRepoBoard': 'Reponun panosuna git',
  'roadmap.task.done': 'Tamamlandı',
  'roadmap.task.current': 'Güncel görev',
  'roadmap.task.remaining': 'Bekleyen görev',
  'roadmap.run': 'Fazı çalıştır',
  'roadmap.pause': 'Duraklat',
  'roadmap.resume': 'Sürdür',
  'roadmap.chip.done': '✓ Bitti',
  'roadmap.chip.running': 'Çalışıyor',
  'roadmap.chip.paused': 'Duraklatıldı',
  'roadmap.chip.attention': '{n} dikkat',
  'roadmap.hint.blocked': 'Önce “{names}” bitmeli',
  'roadmap.hint.paused': 'Yeni iş başlamaz',
  'roadmap.confirm.tasks': '{n} görev',
  'roadmap.confirm.tasksTail': ' başlayacak, ',
  'roadmap.confirm.orders': '{m} iş emri',
  'roadmap.confirm.ordersTail': ' açılıp sıraya girecek.',
  'roadmap.confirm.note': 'Ücretli bir model gerekirse izin ayrıca sorulur. Sonraki faz başlamaz.',
  'roadmap.confirm.go': 'Başlat',
  'roadmap.confirm.cancel': 'Vazgeç',
  'roadmap.attention.title': 'Dikkat isteyen iş emirleri',
  'roadmap.attention.failed': 'başarısız. Faz sürüyor, bağımsız görevler devam ediyor.',
  'roadmap.toast.running': 'Faz çalışıyor: {phase}',
  'roadmap.toast.queued': '{n} görev · {m} iş emri sıraya girdi',
  'roadmap.toast.failed': '{k} görev açılamadı',
  'roadmap.toast.paused': 'Faz duraklatıldı',
  'roadmap.toast.pausedSub': 'Çalışan işler bitene kadar sürer; yeni iş başlamaz',
  'roadmap.toast.resumed': 'Faz sürüyor',
  'cockpit.section.attention': 'Senden bekleyenler',
  'cockpit.section.running': 'Koşanlar',
  'cockpit.section.projects': 'Projeler',
  'cockpit.section.closed': 'Son kapananlar',
  'cockpit.section.queued': 'Sırada',
  'cockpit.attention.empty': 'Senden bekleyen yok',
  'cockpit.running.empty': 'Şu an koşan yok',
  'cockpit.projects.empty': 'Henüz proje yok.',
  'cockpit.closed.empty': 'Henüz kapanan iş yok',
  'cockpit.loading': 'Yükleniyor…',
  'cockpit.head.waiting': 'bekliyor',
  'cockpit.head.running': 'koşuyor',
  'cockpit.card.active': 'aktif',
  'cockpit.head.blocked': 'durdu',
  'cockpit.head.ok': 'Her şey yolunda',
  'cockpit.head.idle': 'Şu an iş yok',
  'cockpit.attention.hint': 'Bir iş karar veya izin istediğinde burada, en üstte belirir.',
  'cockpit.running.hint': 'Bir aşama başladığında hesabı ve süresiyle burada görünür.',
  'cockpit.closed.hint': 'Biten iş emirleri burada son beşiyle listelenir.',
  'cockpit.ask.wants': 'Şunu çalıştırmak istiyor',
  'cockpit.head.queued': 'sırada',
  'cockpit.queued.queue': 'sırada',
  'cockpit.queued.limit': 'limit dolu',
  'cockpit.queued.limitAt': 'limit dolu, açılış',
  'cockpit.closed.merged': 'birleştirildi',
  'cockpit.closed.cancelled': 'iptal edildi',
  'cockpit.card.lastActivity': 'son hareket',
  'cockpit.more': 'Tümünü göster',
  'cockpit.less': 'Daha az göster',
  'cockpit.card.repos': 'depo',
  'cockpit.card.singleRepo': 'tek depo',
  'cockpit.card.toRoadmap': 'yol haritası',
  'cockpit.card.toBoard': 'pano',
  'cockpit.error.title': 'Kokpit güncellenemedi.',
  'cockpit.error.empty': 'Veri yüklenemedi. Bağlantıyı kontrol edip yeniden dene.',
  'cockpit.error.stale': 'Gösterilen veri eski, yeni değişiklikler görünmüyor olabilir. Son yükleme:',
  'cockpit.error.unavailable': 'Yüklenemedi',
  'cockpit.first.title': 'İlk projeni ekle',
  'cockpit.first.body': 'Bilgisayarındaki bir klasörü bağla ya da yeni bir proje oluştur. Docket dosyalarının üstüne asla yazmaz.',
  'cockpit.card.waiting': 'bekliyor',
  'board.loading': 'Yükleniyor…',
  'board.view.aria': 'Görünüm',
  'board.view.kanban': 'Kanban',
  'board.view.liste': 'Liste',
  'board.roadmap': 'Yol haritası ↗',
  'board.roadmap.title': 'Projenin yol haritasını aç',
  'board.editProject': 'Projeyi düzenle',
  'board.editProject.title': "Projeyi düzenle · Ayarlar'da açılır",
  'board.new': '+ Yeni iş emri',
  'board.done.jobs': 'iş emri',
  'board.empty.stage': 'Bu aşamada iş yok.',
  'board.list.col.code': 'Kod',
  'board.list.col.title': 'Başlık',
  'board.list.col.status': 'Durum',
  'board.list.empty': 'Bu repoda henüz iş emri yok.',
  'board.list.running': 'koşuyor',
  'board.list.waiting': 'bekliyor',
  'board.column.collapse': 'Daralt',
  'board.column.expand': 'Aç',
  'board.column.locked': 'Bekleyen iş var, açık kalır',
  'board.column.shut': 'daraltılmış',
  'board.column.done': 'Bitti',
  'board.create.title': 'Yeni iş emri',
  'board.create.titleLabel': 'Başlık',
  'board.create.titlePlaceholder': 'iş emri başlığı',
  'board.create.flowLabel': 'Akış',
  'board.create.flowPlaceholder': 'akış',
  'board.create.submit': 'Aç',
  'action.retry': 'Yeniden dene',
  'action.open': 'Aç',
  'success.workOrder.open': 'İş emri açıldı.',
  'success.workOrder.block': 'İş emri engellendi.',
  'success.workOrder.unblock': 'İş emrinin engeli kaldırıldı.',
  'success.workOrder.close': 'İş emri kapatıldı.',
  'success.workOrder.enqueue': 'Aşama kuyruğa alındı.',
  'success.task.open': 'Görevün iş emirleri açıldı.',
  'success.project.attach': 'Proje eklendi.',
  'success.repo.register': 'Depo kaydı yapıldı.',
  'success.repo.unregister': 'Depo kaydı kaldırıldı.',
  'success.gate.decide': 'Kapı kararı kaydedildi.',
  'success.proposal.decide': 'Teklif kararı kaydedildi.',
  'success.permission.answer': 'İzin yanıtı kaydedildi.',
  'success.deploy.approve': 'Dağıtım onaylandı ve çalıştırıldı.',
  'nav.settings': 'Ayarlar',
  'settings.close': 'Ayarları kapat',
  'settings.section.accounts': 'Hesaplar',
  'settings.accounts.empty': 'Henüz hesap yok.',
  'settings.meters.empty': 'Bu hesap için ölçüm yok.',
  'settings.meter.remaining': 'kalan',
  'settings.meter.resetsAt': 'yenilenme',
  'meter.value.percent': '%{value}',
  'meter.value.unit': '{value} {unit}',
  'meter.unit.credits': 'kredi',
  'meter.unit.tokens': 'token',
  'meter.unit.requests': 'istek',
  'meter.unit.prompts': 'istem',
  'meter.unit.minutes': 'dakika',
  'settings.account.remove': 'Hesabı kaldır',
  'settings.remove.warning': 'Bu hesap şu rol bağlantılarında kullanılıyor:',
  'settings.remove.updateRoles': "Roller'de bağlantıyı güncelle",
  'settings.remove.onlyAccount': 'Bu tek hesap: önce rollere başka bir hesap bağla, sonra kaldır.',
  'settings.remove.cancel': 'Vazgeç',
  // Hesap kartının model listesi ve harcama onayı (P-40).
  'settings.models.default': 'Varsayılan model',
  'settings.models.empty': 'Bu hesap için listelenecek model yok.',
  'settings.models.stale': 'Güncel olmayabilir',
  'settings.models.refresh': 'Yenile',
  'settings.models.metered': 'Bu model planında dahil değil; kullanım başına faturalandırılır.',
  'settings.models.unknown': 'Planının bu modeli kapsayıp kapsamadığı doğrulanamadı; kullanımı faturalandırılabilir.',
  'settings.models.allowed': 'İzinli',
  'settings.models.revoke': 'Geri al',
  'settings.models.select': 'İzin ver…',
  'settings.models.group.included': 'Plana dahil',
  'settings.models.group.metered': 'Kullanım başına ücretli',
  'settings.models.group.unknown': 'Doğrulanamadı',
  'settings.models.consent.capNeeded': 'Bu hesabın harcama tavanı yok; izin için bir tavan gerekir. Önerilen değer dolduruldu.',
  'settings.models.consent.capHas': 'Bu hesabın harcama tavanı zaten tanımlı; izin onunla sınırlı kalır.',
  'settings.models.consent.title': 'Harcama onayı',
  'settings.models.consent.body': 'Yalnızca elle seçtiğin bir rol bu modeli kullanır; kademeler ve yedekler onu asla kendiliğinden seçmez.',
  'settings.models.consent.scope': 'Üst sınır dönemi',
  'settings.models.consent.amount': 'Tutar (USD)',
  'settings.models.consent.amountPlaceholder': '0,00',
  'settings.models.consent.amountHint': 'Tutar sıfırdan büyük bir sayı olmalı.',
  'settings.models.consent.allow': 'İzin ver',
  'settings.models.consent.cancel': 'Vazgeç',
  'cap.scope.account_day': 'Günlük',
  'cap.scope.account_week': 'Haftalık',
  'cap.scope.account_month': 'Aylık',
  'tier.strong': 'güçlü',
  'tier.balanced': 'dengeli',
  'tier.fast': 'hızlı',
  'settings.section.phone': 'Telefon',
  'settings.phone.none': 'Telefon bağlı değil',
  'settings.phone.explain':
    'Docket telefonu ayrı bir uygulamadır; eşleştirme hazır olduğunda buradan bağlanacak.',
  'settings.phone.pair': 'Eşleştir',
  'settings.phone.soon': 'Yakında',
  'settings.section.update': 'Güncelleme',
  'settings.update.version': 'Sürüm',
  'settings.update.status.none': 'Docket güncel.',
  'settings.update.status.available': 'Yeni bir sürüm indirilebilir:',
  'settings.update.status.downloading': 'İndiriliyor',
  'settings.update.status.ready': 'Güncelleme hazır — yeniden başlatın.',
  'settings.update.status.error': 'Güncelleme durumu öğrenilemedi.',
  'settings.update.check': 'Şimdi kontrol et',
  'update.error.offline': 'Çevrimdışı.',
  'update.error.failed': 'Kontrol başarısız.',
  'update.button.now': 'Güncelle',
  'update.button.restart': 'Yeniden başlat',
  'settings.language.label': 'Dil',
  'settings.language.tr': 'Türkçe',
  'settings.language.en': 'English',
  'editor.back': '‹ Hesaplar',
  'editor.openView': 'Hesap görünümünü aç',
  'editor.tab.general': 'Genel',
  'editor.tab.usage': 'Kullanım',
  'editor.tab.limits': 'Limitler',
  'editor.tab.models': 'Modeller',
  'editor.head.diffs': '{n} ayar önerilenden farklı',
  'editor.head.clean': 'Bu hesap önerilen ayarlarla çalışıyor.',
  'editor.resetAll': 'Hepsini önerilene döndür',
  'editor.reset': 'Önerilene dön',
  'editor.differs': 'Önerilenden farklı · önerilen: {value}',
  'editor.saved': 'Kaydedildi',
  'editor.recommended': 'Önerilen',
  'editor.general.label': 'Ad',
  'editor.general.labelHint': 'Listelerde bu ad görünür.',
  'editor.general.roles': "Roller",
  'editor.general.rolesHint': "Bu hesabı kullanan roller; birine tıklamak İnce ayarını açar.",
  'editor.fact.provider': 'Sağlayıcı',
  'editor.fact.connection': 'Bağlantı',
  'editor.fact.plan': 'Plan',
  'editor.fact.identityDir': 'Kimlik klasörü',
  'editor.fact.endpointHost': 'Uç nokta',
  'editor.fact.secret': 'Anahtar',
  'editor.fact.secret.yes': 'Anahtar zincirinde kayıtlı',
  'editor.fact.secret.no': 'Kayıtlı anahtar yok',
  'editor.usage.lastRead': 'Son okuma',
  'editor.usage.refresh': 'Yenile',
  'editor.usage.spend': 'Bu dönemin harcaması',
  'editor.usage.spendNone': 'Harcama okunmadı',
  'editor.usage.cap': 'tavan',
  'editor.usage.noCap': 'tavan yok',
  'editor.meter.reserveNote': '%{share} senin için ayrılmış',
  'editor.meter.reached': 'Rezerve ulaştı — yeni koşu başlamaz',
  'editor.limits.policy.title': 'Limit dolunca',
  'editor.limits.policy.purpose': 'Bir sayaç dolduğunda bu hesapla ne yapılacağı.',
  'editor.policy.purpose.wait_resume': 'Bekler; limit sıfırlanınca kaldığı yerden sürdürür.',
  'editor.policy.purpose.switch_pool': 'Dolan limit bir modele aitse, aynı hesapta limiti olan başka bir modelle sürer.',
  'editor.policy.purpose.fallback_account': 'Sıradaki hesaba geçer. Ücretli ya da doğrulanmamış hesaplara kendiliğinden geçmez.',
  'editor.policy.purpose.ask': 'Durur ve kokpitte senden karar bekler.',
  'editor.limits.reserve.title': 'Kendi kullanımın için ayır',
  'editor.limits.reserve.purpose': 'Docket bu payı kullanmaz; yeni koşu payın dolunca başlamaz.',
  'editor.limits.reserve.none': 'Yok',
  'editor.limits.reserve.preset': '%{value}',
  'editor.limits.reserve.split': 'Pencereye göre ayrı…',
  'editor.limits.reserve.fineTune': 'İnce ayar',
  'editor.limits.reserve.shortField': 'Kısa pencere (%)',
  'editor.limits.reserve.longField': 'Uzun pencere (%)',
  'editor.limits.reserve.fieldHint': '0–95 arası tam sayı.',
  'editor.limits.reserve.larger': 'büyük olan geçerli',
  'editor.limits.reserve.noMeters': 'Bu hesapta bu pencereden sayaç yok.',
  'editor.limits.reserve.invalid': '0–95 arası tam sayı yazın.',
  'error.invalid_reserve': 'Ayrılan pay 0 ile %95 arasında olmalı.',
  'editor.limits.cap.title': 'Harcama tavanı',
  'editor.limits.cap.purpose': 'Bu hesapta bir dönemde harcanabilecek en çok tutar.',
  'editor.limits.cap.amount': 'Tutar (USD)',
  'editor.limits.cap.amountPlaceholder': '50',
  'editor.limits.cap.period': 'Dönem',
  'editor.limits.cap.period.account_day': 'Gün',
  'editor.limits.cap.period.account_week': 'Hafta',
  'editor.limits.cap.period.account_month': 'Ay',
  'editor.limits.cap.warn': 'Uyarı eşiği (%)',
  'editor.limits.cap.warnHint': 'Tavanın bu yüzdesine gelince uyarır; 1–100.',
  'editor.limits.cap.invalidAmount': 'Sıfırdan büyük bir tutar yazın.',
  'editor.limits.cap.invalidWarn': '1–100 arası tam sayı yazın.',
  'editor.limits.p40note': 'Otomatik geçiş, plana dahil bir modelden ücretli ya da doğrulanamamış bir modele asla geçmez.',
  'editor.policy.wait_resume': 'Sıfırlanınca sürdür',
  'editor.policy.switch_pool': 'Aynı hesapta başka modele geç',
  'editor.policy.fallback_account': 'Sıradakine geç',
  'editor.policy.ask': 'Durdur ve bana sor',
  'editor.value.reserve': '%{short} · %{long}',
  'editor.value.cap': '${amount} · {scope}',
  'editor.value.warn': '%{value}',
  'editor.status.ready': 'Hazır',
  'editor.status.reserve': 'Rezerve ulaştı',
  'editor.status.noData': 'Veri yok',
  'settings.group.work': 'Çalışma',
  'settings.group.app': 'Uygulama',
  'settings.section.roles': 'Roller',
  'settings.section.capabilities': 'Yetenekler',
  'settings.section.providers': 'Sağlayıcılar',
  'settings.section.appearance': 'Görünüm',
  'settings.accounts.dot': 'Henüz eklenmemiş hesap var',
  'candidates.title': "Eklenmemiş",
  'candidates.empty': "Eklenecek hesap bulunamadı.",
  'candidates.rescan': "Yeniden tara",
  'candidates.scan.title': 'Asistanlar ve hesaplar taranıyor…',
  'candidates.scan.done': '{n} hesap bulundu',
  'candidates.add': "Ekle",
  'candidates.status.ready': "Hazır",
  'candidates.status.key_needed': "Anahtar gerekli",
  'candidates.status.unreadable': "Okunamıyor",
  'candidates.status.needs_login': "Giriş gerekli",
  'candidates.status.not_installed': "Kurulu değil",
  'candidates.status.unknown': "Durum bilinmiyor",
  'candidates.status.scanning': 'Taranıyor…',
  'candidates.reason.unreadable': "Yapılandırma klasörü okunamadı; erişim iznini kontrol edip yeniden tara.",
  'candidates.warn.env_overrides_login': "Ortam değişkeni girişi geçersiz kılıyor",
  'candidates.info.env_overrides_login': "Bu klasördeki oturum açma yerine ortam değişkenleri kullanılıyor. Hesap eklenir, ancak çalışırken ortamdaki değerler öncelik alır.",
  'candidates.keymove.title': "Erişim anahtarını Anahtar Zinciri'ne taşı",
  'candidates.keymove.body': "Açıkken anahtar yalnızca işletim sisteminin Anahtar Zinciri'nde saklanır. Değeri hiçbir yerde gösterilmez.",
  'candidates.keymove.switch': "Anahtarı taşı",
  'candidates.hint.login': 'Terminalde {name} ile giriş yap, sonra Yeniden tara.',
  'providers.rescan': "Yeniden tara",
  'providers.scanning': "taranıyor",
  'providers.empty': "Sağlayıcı bulunamadı.",
  'providers.failed': "Tarama başarısız oldu.",
  'providers.status.ready': "Hazır",
  'providers.status.needs_login': "Giriş gerekli",
  'providers.status.unverified': "Doğrulanamadı",
  'providers.status.not_installed': "Kurulu değil",
  'providers.group': "Kurulu değil",
  'providers.copy': "Kopyala",
  'settings.theme.label': 'Tema',
  'settings.theme.system': 'Sistem',
  'settings.theme.dark': 'Koyu',
  'settings.theme.light': 'Açık',
  'source.pushed': 'gönderildi',
  'source.polled': 'sorgulandı',
  'source.header': 'başlık',
  'source.captured_from_error': 'hatadan yakalandı',
  'source.estimated': 'tahmini',
  'source.documented_rule': 'belgelenmiş kural',
  'source.unknown': 'bilinmiyor',
  'auth.mode.subscription': 'Abonelik',
  'auth.mode.api_key': 'API anahtarı',
  'auth.mode.cloud': 'Bulut',
  'auth.mode.byok': 'Kendi anahtarın',
  'wizard.title': 'Kurulum',
  'wizard.checking': 'Kontrol ediliyor…',
  'wizard.step.welcome': 'Hoş geldin',
  'wizard.step.accounts': 'Hesaplar',
  'wizard.step.capabilities': 'Yetenekler',
  'wizard.step.order': 'Asistan sırası',
  'wizard.step.budget': 'Bütçe',
  'wizard.rail.skipped': '–',
  'wizard.back': 'Geri',
  'wizard.skip': 'Bu adımı atla',
  'wizard.next': 'Devam',
  'wizard.finish': 'Kurulumu bitir',
  'wizard.finishing': 'Kuruluyor…',
  'wizard.reason.accounts': 'Devam etmek için hazır bir hesap seç.',
  'wizard.reason.capabilities': 'Yetenekler okunuyor…',
  'wizard.reason.budget': 'Kullandıkça öde hesapları için harcama izni ve tavan gerekli.',
  'wizard.welcome.lead': 'Docket bilgisayarındaki yapay zekâ asistanlarını senin belirlediğin adımlarla çalıştırır. Önemli kararlar hep senden gelir.',
  'wizard.accounts.lead': "Asistanları ve her birinin hesaplarını otomatik buldum. Docket'in kullanacaklarını seç.",
  'wizard.capabilities.lead': 'Kurulu asistanlarda bulunan yetenekler. Kullanmak istediklerini işaretle.',
  'wizard.capabilities.count': '{n} yetenek',
  'wizard.capabilities.truncated': 'Liste kısaltıldı',
  'wizard.capabilities.added': 'Eklendi',
  'wizard.capabilities.command': 'Komut',
  'wizard.capabilities.path': 'Yol',
  'wizard.capabilities.sources': 'Kaynaklar',
  'wizard.capabilities.rejected.note': 'Şu yetenekler eklenemedi:',
  'wizard.capabilities.rejected.toast': 'Şu yetenekler eklenemedi: {list}',
  'wizard.capabilities.reject.not_found': 'bulunamadı',
  'wizard.capabilities.reject.invalid_name': 'adı geçersiz',
  'wizard.capabilities.reject.id_taken': 'adı başka bir yetenekte',
  'wizard.capabilities.reject.missing_command': 'komutu eksik',
  'wizard.capabilities.reject.missing_path': 'yolu eksik',
  'wizard.capabilities.reject.invalid_definition': 'tanımı geçersiz',
  'wizard.capabilities.reject.other': 'eklenemedi',
  'wizard.order.lead': 'İşleri önce birinci sıradaki hesap yapar; limiti dolunca sıradakine geçer. Sürükleyerek sırala.',
  'wizard.budget.subscriptions': 'Abonelikler',
  'wizard.budget.subscriptionsHint': 'Planına dahil kullanım; para harcamaz.',
  'wizard.budget.payPerUse': 'Kullandıkça öde ya da ücreti bilinmeyen',
  'wizard.budget.payPerUseHint': 'Para harcayabilir; tavan ve iznin olmadan çalışmaz.',
  'wizard.consent.allow': 'İzin ver',
  'wizard.consent.granted': 'İzinli',
  'wizard.consent.revoke': 'Geri al',
  'wizard.editor.cancel': 'Vazgeç',
  'wizard.editor.save': 'Kaydet',
  'discovery.found': 'bulundu',
  'discovery.missing': 'bulunamadı',
  'discovery.loggedIn': 'giriş yapılmış',
  'discovery.loginRequired': 'giriş gerekli',
  'discovery.loginUnknown': 'giriş durumu bilinmiyor',
  'errorBoundary.title': 'Uygulama beklenmeyen bir hatayla karşılaşt.',
  'errorBoundary.reload': 'Yeniden yükle',
  'success.account.save': 'Hesap kaydedildi.',
  'success.account.adopt': 'Hesap eklendi.',
  'success.capabilities.import': 'Yetenekler içe aktarıldı.',
  'success.account.remove': 'Hesap kaldırıldı.',
  'success.account.consent.grant': 'Harcama onayı verildi.',
  'success.account.consent.revoke': 'Harcama onayı kaldırıldı.',
  'success.binding.save': 'Rol bağlantısı kaydedildi.',
  'success.app.update.check': 'Güncellemeler kontrol edildi.',
  'success.app.update.apply': 'Güncelleme indirmesi başladı.',
  'error.empty_chain': 'Bir rolün hesap sırası boş olamaz.',
  'error.unknown_project': 'Proje bulunamadı.',
  'error.no_roadmap': 'Bu projenin yol haritası yok.',
  'error.unknown_phase': 'Bu faz yol haritasında yok.',
  'error.phase_not_runnable': 'Bu faz şu an çalıştırılamaz: önceki faz bitmeli ya da faz zaten bitti.',
  'error.not_running': 'Faz çalışmıyor; duraklatılamaz.',
  'error.not_paused': 'Faz duraklatılmış değil; sürdürülemez.',
  'roles.chain.title': 'Asistan sırası',
  'roles.chain.purpose': 'Tüm rollerin kullandığı hesap sırası. İlk hesap önce denenir.',
  'roles.chain.empty': 'Henüz hesap yok. Önce Hesaplar bölümünden bir hesap ekle.',
  'roles.chain.unbound': 'Hesap var ama sıra boş. Önerilen kurulumu uygula ya da ince ayardan bir hesap seç.',
  'roles.chain.up': 'Yukarı taşı: {name}',
  'roles.chain.down': 'Aşağı taşı: {name}',
  'roles.chain.add': 'Sıraya eklemek için bir hesap seç.',
  'roles.empty': 'Henüz rol yok.',
  'roles.style.title': 'Çalışma biçimi',
  'roles.unset.line': '{n} rol önerilen çalışma biçimini kullanmıyor',
  'roles.unset.apply': 'Önerilenleri uygula',
  'roles.style.fast': 'Hızlı',
  'roles.style.balanced': 'Dengeli',
  'roles.style.careful': 'Özenli',
  'roles.style.custom': 'Özel',
  'roles.fine': 'İnce ayar',
  'roles.chainMode.title': 'Hesap sırası',
  'roles.chainMode.all': 'Tüm roller',
  'roles.chainMode.own': 'Bu role özel',
  'roles.model.default': 'Varsayılan model',
  'roles.model.paidLocked': '{model} · izin gerekir',
  'roles.model.hint': 'Ücretli ($) ve doğrulanamayan (?) modeller, hesabın Modeller sekmesinde izin verilince seçilebilir.',
  'roles.tier.title': 'Kademe',
  'roles.tier.unset': 'Belirtilmemiş',
  'roles.thinking.title': 'Düşünme',
  'roles.thinking.unset': 'Belirtilmemiş',
  'roles.thinking.level.fast': 'Hızlı',
  'roles.thinking.level.balanced': 'Dengeli',
  'roles.thinking.level.deep': 'Derin',
  'roles.thinking.effort': 'Efor: {value}',
  'roles.stages.title': 'Kendi ayarı olan aşamalar',
  'roles.stages.note': 'Akış tanımından gelir; burada değiştirilmez.',
  'roles.stages.line': '{flow} › {stage}',
  'roles.review.sameProvider': 'İnceleme, kodu yazan sağlayıcıda çalışacak. Başka sağlayıcıdan bir hesap eklersen oraya gider.',
  'reset.line': "{time}'{suffix} sıfırlanır · {left} kaldı",
  'reset.unit.d': '{n} gün',
  'reset.unit.h': '{n} sa',
  'reset.unit.m': '{n} dk',
  'editor.danger.title': 'Tehlikeli bölge',
  'editor.danger.remove': "Hesabı Docket'ın listesinden çıkarır.",
  'newProject.title': 'Yeni proje',
  'newProject.copy': "Docket'in çalışacağı projeyi seç ya da yenisini birlikte kuralım.",
  'newProject.featured': 'Birlikte sıfırdan başla',
  'newProject.featured.chip': "Docket'e özel",
  'newProject.featured.sub': 'Fikrini anlat; projeyi, rolleri ve akışı adım adım birlikte kuralım.',
  'newProject.soon': 'Yakında',
  'newProject.divider': 'ya da var olan bir yoldan başla',
  'newProject.existing': 'Var olan klasör',
  'newProject.existing.desc': 'Bilgisayarındaki projeyi bağla.',
  'newProject.clone': "Git'ten klonla",
  'newProject.clone.desc': 'Adresten indir.',
  'newProject.blank': 'Boş proje',
  'newProject.blank.desc': 'Yeni klasör oluştur.',
  'newProject.folder': 'Klasör',
  'newProject.folder.placeholder': '/yol/proje',
  'newProject.name': 'Proje adı',
  'newProject.location': 'Konum',
  'newProject.location.placeholder': '/yol/üst-klasör',
  'newProject.blank.note': 'Konum içinde yeni bir klasör oluşturulacak.',
  'newProject.gate.folder': 'Bir klasör seç.',
  'newProject.gate.name': 'Projeye bir ad ver.',
  'newProject.gate.location': 'Bir konum yaz.',
  'newProject.create': 'Oluştur',
  'newProject.creating': 'Oluşturuluyor…',
  'newProject.cancel': 'Vazgeç',
  'newProject.attach': 'Bağla',
  'newProject.created': "Proje oluşturuldu. Test komutlarını .docket/repo.yaml'a yaz; yazılana kadar test kapısı bekler.",
  'toast.close': 'Kapat',
  'toast.copy': 'Kodu kopyala',
  'toast.copied': 'Kopyalandı',
  'success.account.test': 'Test tamamlandı.',
  'editor.status.modelError': 'Model hatası',
  'accountTest.button': 'Test et',
  'accountTest.running': 'Test ediliyor…',
  'accountTest.untested': 'Test edilmedi',
  'accountTest.ok': 'Çalışıyor',
  'accountTest.defaultModel': 'asistanın varsayılanı',
  'accountTest.class.auth': 'Giriş gerekli ya da anahtar geçersiz',
  'accountTest.class.limit': 'Bu model şu an kullanılamıyor — plan limiti',
  'accountTest.class.model': 'Bu model bu hesapta kullanılamıyor',
  'accountTest.class.network': 'Bağlantı kurulamadı ya da yanıt gelmedi',
  'accountTest.class.install': 'Asistan bu makinede çalıştırılamadı',
  'accountTest.class.unknown': 'Test başarısız oldu',
  'accountTest.detail': 'Ayrıntı',
  'accountTest.openModels': 'Modeller',
  'accountTest.refusal.needs_spend_consent': "Bu model ücretli ya da doğrulanmadı — önce Modeller'de izin ve tavan ver",
  'accountTest.refusal.spend_cap_reached': 'Harcama tavanı doldu',
  'accountTest.refusal.busy': 'Test zaten sürüyor',
  'accountTest.refusal.unsupported': 'Bu hesap test edilemiyor',
  'candidates.hint.testLater': "Giriş durumu okunamıyor. Kurulumdan sonra Ayarlar'da test edebilirsin.",
  'wizard.railNote': "Seçimlerinin hepsini sonra Ayarlar'dan değiştirebilirsin.",
  'wizard.budget.lead': 'Her hesap için limit dolunca ne olacağını ve harcama tavanını belirle. Önerilenler güvenli.',
  'wizard.order.note': "Tüm roller bu sırayı kullanır; role özel sırayı Ayarlar'da verirsin. Kullandıkça öde hesaplar otomatik geçişte atlanır, onları ancak sen seçersin.",
  'wizard.order.first': 'İlk tercih',
  'wizard.order.skipsAuto': 'otomatik geçişte atlanır',
  'wizard.budget.cap': 'Tavan',
  'wizard.budget.period': 'Dönem',
  'wizard.budget.capNote': "Tavanın %80'ine gelince haber veririm; tavana ulaşınca yeni işleri durdururum, çalışanı kesmem.",
  'wizard.budget.hint': 'Önerilen ayarlar uygulandı — değiştirmek istersen satırı aç.',
  'wizard.budget.detail': 'Ayrıntı',
  'wizard.budget.summary.policy.wait_resume': 'Limit dolunca bekler',
  'wizard.budget.summary.policy.fallback_account': 'Limit dolunca sıradakine geçer',
  'wizard.budget.summary.policy.switch_pool': 'Limit dolunca model değiştirir',
  'wizard.budget.summary.policy.ask': 'Limit dolunca durur ve sorar',
  'wizard.budget.summary.reserveNone': 'rezerv yok',
  'wizard.budget.summary.reserve': 'rezerv %{p}',
  'wizard.budget.summary.capAllowed': 'Tavan ${c} · izinli',
  'wizard.budget.summary.capAwaiting': 'Tavan ${c} · izin bekliyor',
  'wizard.finish.title': 'Kurulum sürüyor',
  'wizard.finish.lead': 'Seçimlerin uygulanıyor; birkaç saniye sürer.',
  'wizard.finish.line.accounts': 'Hesaplar kaydediliyor',
  'wizard.finish.line.capabilities': 'Yetenekler ekleniyor',
  'wizard.finish.line.order': 'Sıra kaydediliyor',
  'wizard.finish.line.budget': 'Bütçe uygulanıyor',
  'wizard.finish.line.home': 'Anasayfa hazırlanıyor',
  'wizard.retry': 'Tekrar dene',
  'appearance.language.hint': 'Arayüzün dili.',
  'appearance.theme.hint': 'Bilgisayarının ayarını izleyebilir ya da sabit kalabilir.',
  'accountGroups.found': 'Bulunanlar',
  'accountGroups.failed': 'Hatalı ve bulunamayanlar',
  'accountGroups.scanned': 'Taranan',
  'accountGroups.added': 'Eklenenler',
  'accountGroups.counts': '{accounts} hesap · {assistants} asistan',
  'accountGroups.count': '{n} hesap',
  'accountGroups.summary.needsLogin': '{n} giriş gerekli',
  'accountGroups.summary.unverified': '{n} doğrulanamadı',
  'accountGroups.edit': 'Düzenle',
  'accountGroups.unknownProvider': 'Bilinmeyen asistan',
  'accountGroups.billing.sub': 'Abonelik',
  'accountGroups.billing.subKey': 'Abonelik · anahtarla',
  'accountGroups.billing.payg': 'Kullandıkça öde',
  'accountGroups.billing.unknown': 'Ücret bilinmiyor',
  'dragOrder.moved': '{n}. sıraya taşındı',
  'dragOrder.keysLead': 'Klavyeyle: satıra odaklan,',
  'meterList.window.five_hour': '5 saatlik',
  'meterList.window.seven_day': 'Haftalık',
  'meterList.window.monthly': 'Bu ay',
  'meterList.scope.all': 'tüm modeller',
  'meterList.scope.model': 'yalnız {model}',
  'meterList.left': 'kalan',
  'meterList.unread': 'Okunamadı',
  'meterList.resetsIn': '{t} sonra sıfırlanır',
  'meterList.modelNote': '{model} limiti dolarsa bu hesapta yalnız {model} durur; diğer modeller çalışmaya devam eder.',
  'meterList.noMeter': 'Bu asistan kullanım bilgisi vermiyor; limit dolunca hatadan anlarız.',
  'meterList.needsLogin': 'Giriş yapılınca limitler görünür.',
  'meterList.afterAdd': 'Limitler hesap eklenince okunur.',
  'editor.general.facts': 'Hesap bilgileri',
  'editor.limits.reserve.custom': 'Özel',
  'editor.footer.draft': 'Değişiklikler kurulum bitince kaydedilir.',
  'editor.footer.saves': 'Değişiklikler hemen kaydedilir.',
  'editor.footer.close': 'Kapat',
  'settings.models.groupHint.included': 'para harcamaz',
  'settings.models.groupHint.metered': 'izin ve tavan ister',
  'settings.models.groupHint.unknown': 'ücreti bilinmiyor',
  'settings.models.includedWeekly': 'haftalık limiti olduğu için planda',
  'settings.models.includedOwn': 'kendi limiti olduğu için planda',
  'settings.hint.accounts': "Docket'in kullandığı hesaplar. Ayrıntı ve limitler için ✎.",
  'settings.hint.roles': 'Her rolün hangi sırayla ve hangi çalışma biçimiyle çalışacağı.',
  'settings.hint.capabilities': "Kurulu asistanlarından bulunan MCP sunucuları, skill'ler, hook'lar ve bağlam belgeleri.",
  'settings.hint.providers': 'Bilgisayarında bulunan asistanlar.',
  'settings.hint.appearance': 'Arayüzün dili ve görünüşü.',
  'settings.hint.phone': 'Yerel ağdaki telefonundan onay ver.',
  'settings.hint.update': "Docket'in sürümü.",
  'settings.capabilities.soonTitle': 'Yetenek keşfi hazırlanıyor',
  'settings.capabilities.soonBody': "Bulunan yetenekleri buradan Docket'e kopyalayacaksın; dosyalarına dokunulmayacak.",
  'wizard.finished.toast': 'Kurulum tamamlandı · {n} hesap hazır',
  'cockpit.first.new': 'Yeni proje',
  'cockpit.first.attach': 'Var olan projeyi bağla',
  'settings.section.concurrency': 'Eşzamanlılık',
  'settings.hint.concurrency':
    'Docket’in aynı anda kaç iş çalıştıracağını sınırlar. Değişiklik bir sonraki turda geçerli olur; çalışan işler kesilmez, fazlası sırada bekler.',
  'error.invalid_limits': 'Sınırlar kabul edilmedi: tavan 1 ile 16 arasında, diğer sınırlar 1 ile tavan arasında olmalı.',
  'error.unknown_account': 'Sınır verilen hesaplardan biri artık yok; bölümü yeniden açıp tekrar dene.',
  'success.settings.setDispatch': 'Eşzamanlılık ayarları kaydedildi.',
  'dispatch.mode.label': 'Mod',
  'dispatch.mode.fixed': 'Sabit',
  'dispatch.mode.auto': 'Otomatik',
  'dispatch.mode.fixedDesc': 'Her zaman aşağıdaki sayı kadar iş paralel çalışır.',
  'dispatch.mode.autoDesc': 'Makine boşken tavan kadar iş paralel çalışır, yoğunken yeni iş başlatma kendiliğinden azalır. Çalışan işler kesilmez.',
  'dispatch.machine.title': 'Bu makine',
  'dispatch.machine.facts': '{cores} çekirdek · {mem} GB bellek · önerilen tavan',
  'dispatch.machine.apply': 'Öneriyi uygula',
  'dispatch.cap.auto': 'Tavan',
  'dispatch.cap.autoDesc': 'Makine boşken aynı anda çalışan en fazla iş',
  'dispatch.cap.fixed': 'Toplam',
  'dispatch.cap.fixedDesc': 'Tüm projelerde aynı anda çalışan en fazla iş',
  'dispatch.perRepo.title': 'Depo başına',
  'dispatch.perRepo.desc': 'Aynı depoda aynı anda çalışan en fazla iş',
  'dispatch.account.title': 'Hesap başına',
  'dispatch.account.desc': 'Bir hesabın aynı anda çalıştırabileceği iş sayısı. Sınırsız bırakırsan yalnızca toplam geçerli olur.',
  'dispatch.account.free': 'Sınırsız',
  'dispatch.account.cap': 'Sınırlı',
  'dispatch.account.empty': 'Henüz hesap yok.',
  'dispatch.step.dec': 'Azalt',
  'dispatch.step.inc': 'Artır',
  'dispatch.status.now': 'Şu an etkin: {effective} / {cap}',
  'dispatch.status.unit': 'iş',
  'dispatch.status.load': 'yük {load}',
  'dispatch.band.free': 'Makine boş',
  'dispatch.band.reduced': 'Makine meşgul',
  'dispatch.band.busy': 'Makine yoğun, yeni iş başlamıyor',
  'dispatch.error.global': 'Tavan 1 ile 16 arasında olmalı.',
  'dispatch.error.perRepo': 'Depo başına sınır tavandan büyük olamaz.',
  'dispatch.error.account': 'Hesap sınırı tavandan büyük olamaz.',
  'dispatch.error.min': 'Sınırlar en az 1 olmalı.',
  'dispatch.reset': 'Varsayılana dön',
  'dispatch.save': 'Kaydet',
  'dispatch.saved': 'Kaydedildi',
  'page.section.title': 'Sayfalar',
  'page.list.version': 'sürüm {n}',
  'page.list.unread': '{n} yorum henüz okunmadı',
  'page.list.unreadOne': '1 yorum henüz okunmadı',
  'page.back': '‹ Geri',
  'page.kind.html': 'html',
  'page.kind.markdown': 'markdown',
  'page.kind.diagram': 'diyagram',
  'page.kind.table': 'tablo',
  'page.kind.image': 'resim',
  'page.kind.report': 'rapor',
  'page.approval.none': 'Onay istenmedi',
  'page.approval.pending': 'Onay bekliyor',
  'page.approval.approved': '✓ Onaylandı · sürüm {n}',
  'page.approval.rejected': 'Reddedildi',
  'page.header.version': 'sürüm {n} · {age}',
  'page.version.label': 'Sürüm',
  'page.version.option': 'Sürüm {n}',
  'page.version.latest': 'Sürüm {n} (son)',
  'page.view.label': 'Görünüm',
  'page.view.preview': 'Önizleme',
  'page.view.diff': 'Fark',
  'page.diff.noPrevious': 'Karşılaştırılacak önceki sürüm yok',
  'page.diff.image': 'Resimlerde fark gösterilmez',
  'page.diff.truncated': 'Fark kısaltıldı',
  'page.diff.region': 'Sürümler arası fark',
  'page.guard.badge': 'izole',
  'page.guard.text': 'Bu sayfa asistan tarafından üretildi ve güvenilmez içerik sayılır: ağa çıkamaz, Docket verilerine erişemez.',
  'page.stage.region': 'Sayfa önizlemesi',
  'page.stage.loading': 'Sayfa yükleniyor…',
  'page.stage.error': 'Sayfa gösterilemedi',
  'page.stage.retry': 'Yeniden dene',
  'page.note.newVersion': 'Yeni sürüm geldi, önceki onay geçersiz. Beğenirsen yeniden onay iste.',
  'page.bar.old': 'Eski sürüm: onay işlemleri yalnızca son sürümde',
  'page.bar.pendingGate': 'Onaylarsan iş emri bir sonraki aşamaya geçer',
  'page.bar.pendingPlain': 'Onaylarsan sayfa onaylı işaretlenir',
  'page.bar.approved': 'Bu sürüm onaylı',
  'page.bar.idle': 'Asistan yeni sürüm yayınlayınca onay isteyebilirsin',
  'page.action.request': 'Onay iste',
  'page.action.reject': 'Reddet',
  'page.action.approve': 'Onayla',
  'page.comments.title': 'Yorumlar',
  'page.comments.count': 'sürüm {n} · {count}',
  'page.comments.empty': 'Bu sürümde yorum yok.',
  'page.comments.emptyHint': 'Yorumların asistana ulaşır, o da yeni sürüm yayınlar.',
  'page.comment.by': 'Sen · {age}',
  'page.comment.delivered': 'asistana iletildi',
  'page.comment.undelivered': 'asistana iletilmedi',
  'page.comment.version': 'sürüm {n}',
  'page.composer.label': 'Yorum',
  'page.composer.placeholder': 'Bu sürüm için yorum yaz',
  'page.composer.hint': 'Yorumunu asistan bir sonraki turda okur; sayfanın içeriği asistana talimat vermez.',
  'page.composer.counter': '{n} / {max}',
  'page.composer.submit': 'Yorum ekle',
  'page.composer.old': 'Eski sürüme yorum eklenmez. Son sürüme geç.',
  'page.toast.commented': 'Yorum eklendi',
  'page.toast.requested': 'Onay istendi',
  'page.toast.approved': 'Sayfa onaylandı',
  'page.toast.approvedAdvanced': 'Sayfa onaylandı · iş emri bir sonraki aşamaya geçti',
  'page.toast.rejected': 'Sayfa reddedildi',
  'page.error.not_found': 'Sayfa bulunamadı.',
  'page.error.not_pending': 'Bu sayfa için bekleyen bir onay yok.',
  'page.error.self_approval': 'Sayfayı yayınlayan onaylayamaz.',
  'library.search.placeholder': 'Ara',
  'library.kind.label': 'Tür',
  'library.kind.all': 'Tümü',
  'library.kind.html': 'Taslak',
  'library.kind.diagram': 'Diyagram',
  'library.kind.markdown': 'Metin',
  'library.kind.table': 'Tablo',
  'library.kind.report': 'Rapor',
  'library.kind.image': 'Resim',
  'library.project.label': 'Proje',
  'library.project.all': 'Tüm projeler',
  'library.view.label': 'Liste',
  'library.view.new': 'Yeni',
  'library.view.pinned': 'Sabitler',
  'library.region': 'Artifact listesi',
  'library.pin': 'Sabitle',
  'library.unpin': 'Sabiti kaldır',
  'library.approval.approved': '✓ Onaylandı',
  'library.provenance.docket_ai': 'Docket AI · sohbet',
  'library.provenance.agent_run': 'asistan',
  'library.provenance.operator': 'sen',
  'library.empty.title': 'Henüz artifact yok',
  'library.empty.body': 'Docket AI’dan bir taslak, diyagram ya da rapor iste; burada birikir.',
  'library.filtered.title': 'Eşleşen artifact yok',
  'library.filtered.body': 'Aramayı ya da süzgeçleri değiştir.',
  'library.error.title': 'Artifact\'lar yüklenemedi.',
  'library.cap': 'İlk {n} artifact gösteriliyor',
  'library.loading': 'Artifact\'lar yükleniyor…',
  'library.toast.pinned': 'Sabitlendi',
  'library.toast.unpinned': 'Sabit kaldırıldı',
  'page.error.too_many_pinned': 'En fazla 200 artifact sabitlenebilir; önce birini kaldır.',
  'error.empty_comment': 'Yorum boş olamaz.',
  'error.comment_too_long': 'Yorum en fazla 4000 karakter olabilir.',
  'error.unknown_version': 'Böyle bir sürüm yok.',
  'error.stale_version': 'Yeni sürüm geldi; önce onu incele.',
  'chat.fab.open': 'Docket AI’ı aç',
  'chat.fab.close': 'Docket AI’ı kapat',
  'chat.panel': 'Docket AI',
  'chat.scope.global': 'Tüm projeler',
  'chat.scope.desc.global': 'Genel bakış',
  'chat.scope.desc.project': 'Bu projenin her şeyi',
  'chat.scope.desc.workOrder': 'Yalnızca bu iş emri',
  'chat.scope.fallback.project': 'Proje',
  'chat.scope.fallback.workOrder': 'İş emri',
  'chat.scope.pinned': 'sabit',
  'chat.scope.attached': 'Eklenenler',
  'chat.scope.follow': 'Bulunduğum ekranı izle',
  'chat.scope.following': 'Bulunduğun ekranı izler',
  'chat.history': 'Geçmiş',
  'chat.new': 'Yeni konuşma',
  'chat.empty.title': 'Ne öğrenmek istersin?',
  'chat.suggest.global.a': 'Benden ne bekleniyor?',
  'chat.suggest.global.b': 'Bu hafta kota nasıl gitti?',
  'chat.suggest.project.a': 'Sıradaki hazır görevler?',
  'chat.suggest.project.b': 'Bütçe ne durumda?',
  'chat.suggest.workOrder.a': 'Neden beklemede?',
  'chat.suggest.workOrder.b': 'Son çalışmada ne değişti?',
  'chat.busy': 'Asistan yazıyor',
  'chat.input.placeholder': 'Sor  ·  @ ile ekle',
  'chat.input.aria': 'Mesaj',
  'chat.add': 'Ekle',
  'chat.send': 'Gönder',
  'chat.stop': 'Durdur',
  'chat.at.section': 'Ekle',
  'chat.at.none': 'Eşleşen bir şey yok. Yalnızca kendi projelerindeki iş emirleri, sayfalar ve dosyalar eklenebilir.',
  'chat.at.hint': 'Aramak için yazmaya devam et.',
  'chat.at.loading': 'Aranıyor…',
  'chat.plus.file': 'Dosya veya resim',
  'chat.plus.file.desc': 'png, jpg, webp, md, txt, log, csv, json, pdf',
  'chat.plus.screen': 'Bu ekranı ekle',
  'chat.plus.screen.desc': 'Ekranın verisi, görüntüsü değil',
  'chat.plus.screen.none': 'Bu ekranın eklenecek verisi yok.',
  'chat.plus.ref': 'İş emri, sayfa, dosya…',
  'chat.plus.ref.desc': 'veya mesajda @ yaz',
  'chat.note.quota': 'Hesabın kotası dolu.',
  'chat.note.quota.action': 'Hesabı değiştir',
  'chat.note.consent': 'Bu model kullanım başına faturalanır.',
  'chat.note.consent.action': 'İzin ver',
  'chat.note.spend': 'Harcama sınırına ulaşıldı.',
  'chat.note.auth': 'Docket AI için kullanılabilir bir hesap yok.',
  'chat.note.limit': 'Yanıt sınıra ulaştığı için yarıda kaldı.',
  'chat.note.network': 'Ağ bağlantısı koptu; yanıt tamamlanamadı.',
  'chat.note.crash': 'Docket AI beklenmedik şekilde durdu.',
  'chat.note.tools_unavailable': 'Bu hesapla Docket araçları kullanılamıyor.',
  'chat.note.dismiss': 'Notu kapat',
  'chat.file.video': 'Video desteklenmiyor. Bir kareyi resim olarak ekleyebilirsin.',
  'chat.file.type': 'Bu dosya türü eklenemez.',
  'chat.file.limit': 'En fazla 5 dosya eklenebilir.',
  'chat.file.image': 'Resim şimdilik modele gönderilmez; adı ve türü iletilir.',
  'chat.ref.remove': '{name} atfını kaldır',
  'chat.file.remove': '{name} dosyasını kaldır',
  'chat.tier.suggest': 'Öner',
  'chat.tier.apply': 'Uygula · {n} dk',
  'chat.usage.month': 'bu ay {n} mesaj',
  'chat.perm.aria': 'Docket AI izinleri',
  'chat.perm.off.title': 'Docket AI ne yapabilir?',
  'chat.perm.off.body': 'Şimdi: her değişiklik önce sana kart olarak gelir (Öner). İstersen bu konuşmada, 1 saate kadar, seçtiklerini kendisi uygulasın.',
  'chat.perm.class.open_work_order': 'İş emri aç',
  'chat.perm.class.open_work_order.desc': 'Onayladığın taslakları kendisi açar',
  'chat.perm.class.roadmap_edit': 'Yol haritasını düzenle',
  'chat.perm.class.roadmap_edit.desc': 'Görev ekler ve günceller',
  'chat.perm.class.definition_edit': 'Akış ve rol dosyaları',
  'chat.perm.class.definition_edit.desc': 'Fark kartı olmadan yazar',
  'chat.perm.class.setting_change': 'Eşzamanlılık ayarı',
  'chat.perm.class.setting_change.desc': 'Yalnızca bu ayar',
  'chat.perm.never': 'Hiçbir zaman: kapı onayı, izin cevabı, birleştirme, silme, hesap ve sır, harcama izni.',
  'chat.perm.cancel': 'Vazgeç',
  'chat.perm.grant': '1 saat izin ver',
  'chat.perm.on.title': 'Uygula açık · {n} dk kaldı',
  'chat.perm.on.body': 'Bu konuşmada şunları kartsız uygular; her biri kayıtlıdır ve geri alınabilir.',
  'chat.perm.revoke': 'İzni kapat',
  'chat.history.search': 'Geçmişte ara',
  'chat.history.group.pinned': 'Sabitlenenler',
  'chat.history.group.today': 'Bugün',
  'chat.history.group.yesterday': 'Dün',
  'chat.history.group.week': 'Bu hafta',
  'chat.history.group.older': 'Daha eski',
  'chat.history.pin': 'Sabitle',
  'chat.history.unpin': 'Sabiti kaldır',
  'chat.history.delete': 'Sil',
  'chat.history.none': 'Eşleşen konuşma yok.',
  'chat.history.empty': 'Henüz konuşma yok.',
  'chat.history.failed': 'Geçmiş okunamadı.',
  'chat.card.page.open': 'Aç',
  'chat.card.page.type': '{kind} · sürüm {n}',
  'chat.card.draft.drop': 'Vazgeç',
  'chat.card.draft.create': 'Oluştur',
  'chat.card.draft.made': '✓ İş emri açıldı',
  'chat.card.draft.dropped': 'Vazgeçildi',
  'chat.card.proposal.source': 'Kaynak: {target}',
  'chat.card.proposal.approve': 'Onayla',
  'chat.card.proposal.reject': 'Reddet',
  'chat.card.proposal.approved': '✓ Onaylandı',
  'chat.card.proposal.rejected': 'Reddedildi',
  'chat.card.proposal.loading': 'Fark yükleniyor…',
  'chat.card.proposal.failed': 'Fark okunamadı.',
  'chat.card.proposal.retry': 'Yeniden dene',
  'chat.card.gone': 'Artık yok',
  'chat.card.table': 'Tablo',
  'chat.action.open_work_order.applied': 'İş emri açıldı',
  'chat.action.roadmap_edit.applied': 'Yol haritası güncellendi',
  'chat.action.definition_edit.applied': 'Akış veya rol dosyası değişti',
  'chat.action.setting_change.applied': 'Ayar değişti',
  'chat.action.pending': 'Değişiklik hazır; onayını bekliyor.',
  'chat.action.failed': 'Değişiklik uygulanamadı.',
  'chat.action.undone': 'Geri alındı',
  'chat.action.undo': 'Geri al',
  'chat.toast.new': 'Yeni konuşma',
  'chat.toast.opened': 'Konuşma açıldı',
  'chat.toast.deleted': 'Konuşma silindi',
  'chat.toast.added': '{name} eklendi',
  'chat.toast.screen': 'Ekranın verisi eklendi',
  'chat.toast.granted': 'Uygula açık · 1 saat',
  'chat.toast.revoked': 'İzin kapandı · yine Öner',
  'chat.toast.undone': 'Geri alındı',
  'chat.toast.approved': 'Öneri onaylandı',
  'chat.toast.rejected': 'Öneri reddedildi',
  'chat.toast.workOrder': 'İş emri açıldı',
  'chat.error.empty_message': 'Mesaj boş olamaz.',
  'chat.error.message_too_long': 'Mesaj çok uzun; en fazla 8000 karakter.',
  'chat.error.message_too_large': 'Mesaj çok uzun; en fazla 8000 karakter.',
  'chat.error.bad_scope': 'Bu kapsam artık yok.',
  'chat.error.bad_ref': 'Eklenen öğelerden biri bulunamadı.',
  'chat.error.too_many_refs': 'En fazla 12 öğe eklenebilir.',
  'chat.error.too_many_attachments': 'En fazla 5 dosya eklenebilir.',
  'chat.error.attachments_too_large': 'Eklerin toplam boyutu çok büyük.',
  'chat.error.attachment_too_large': 'Dosya çok büyük; en fazla 5 MB.',
  'chat.error.bad_attachment': 'Bu dosya eklenemez.',
  'chat.error.bad_base64': 'Bu dosya okunamadı.',
  'chat.error.bad_input': 'İstek geçersiz.',
  'chat.error.busy': 'Docket AI bu konuşmada zaten yanıt veriyor.',
  'chat.error.too_many_turns': 'Aynı anda çok fazla yanıt sürüyor; biraz bekle.',
  'chat.error.not_found': 'Konuşma ya da kayıt bulunamadı.',
  'chat.error.not_pending': 'Bu öneri artık beklemede değil.',
  'chat.error.not_applied': 'Bu değişiklik uygulanmış durumda değil.',
  'chat.error.undo_expired': 'Geri alma süresi doldu.',
  'chat.error.rate_limited': 'Çok hızlı; biraz bekle.',
  'chat.error.grant_empty': 'En az bir izin seç.',
  'chat.error.grant_too_long': 'İzin en fazla 1 saat olabilir.',
  'chat.error.grant_expired': 'İznin süresi doldu.',
  'chat.error.grant_revoked': 'İzin zaten kapatıldı.',
  'chat.error.bad_class': 'Bu izin sınıfı yok.',
  'chat.error.conversation_full': 'Bu konuşma doldu; yeni bir konuşma başlat.',
  'chat.ref.fallback.page': 'Sayfa',
  'nav.proposals': 'Öneriler',
  'proposals.title': 'Öneriler',
  'proposals.tabs.label': 'Öneri sekmeleri',
  'proposals.tab.pending': 'Bekleyen',
  'proposals.tab.decided': 'Karar verilen',
  'proposals.tab.stale': 'Bayat',
  'proposals.list.label': 'Öneri listesi',
  'proposals.empty': 'Öneri yok',
  'proposals.empty.tab': 'Bu sekmede öneri yok',
  'proposals.loading': 'Yükleniyor',
  'proposals.error.title': 'Öneriler okunamadı',
  'proposals.scope.global': 'Genel',
  'proposals.chip.pending': 'Bekliyor',
  'proposals.chip.approved': '✓ Onaylandı',
  'proposals.chip.rejected': 'Reddedildi',
  'proposals.chip.stale': 'Bayat',
  'proposals.diff.label': 'Fark',
  'proposals.diff.truncated': 'Fark kısaltıldı',
  'proposals.note.stale': 'Dosya değişti; öneri geçersiz.',
  'proposals.hint.pending': 'Onaylarsan dosya yazılır',
  'proposals.hint.stale': 'Önce güncel hâli gerek',
  'proposals.approve': 'Onayla',
  'proposals.reject': 'Reddet',
  'proposals.toast.approved': 'Onaylandı',
  'proposals.toast.rejected': 'Reddedildi',
  'proposals.fail.stale': 'Dosya değişti; öneri bayat.',
  'proposals.fail.not_found': 'Öneri artık yok.',
  'proposals.fail.generic': 'Karar kaydedilemedi.',
  'launch.together': 'Docket AI ile birlikte kur',
  'launch.plan': 'Docket AI ile planla',
  'launch.describe': 'Tarif et, ben açayım',
  'launch.whyWaiting': 'Bu neden beklemede?',
  'launch.whatDoing': 'Ne yapıyor?',
  'launch.setup': 'Bunu benim için ayarla',
  'launch.fixComments': 'Yorumlarımı düzelt',
  'launch.prefill.together': 'Yeni bir proje kurmak istiyorum, birlikte yapalım.',
  'launch.prefill.plan': 'Bu proje için bir yol haritası taslağı hazırla.',
  'launch.prefill.describe': 'Şunu yapmak istiyorum: ',
  'launch.prefill.whyWaiting': 'Bu iş emri neden beklemede?',
  'launch.prefill.whatDoing': 'Bu çalışma şu an ne yapıyor?',
  'launch.prefill.setup': '{section} ayarını benim için yapılandır.',
  'launch.prefill.fixComments': 'Sayfadaki yorumlarımı gözden geçirip düzelt.',
};
