// labels/tr.ts — Turkish bundle. Turkish is the default locale; every key of keys.ts carries copy.
import type { LabelBundle } from './keys';

export const TR: LabelBundle = {
  'error.invalid_id': 'Geçersiz kimlik.',
  'error.definitions_invalid': 'Tanımlar geçersiz; proje tanımı okunamadı.',
  'error.unknown_flow': 'Bilinmeyen akış.',
  'error.flow_not_enabled': 'Bu akış bu repoda etkin değil.',
  'error.unknown_task': 'Bilinmeyen görev.',
  'error.empty_title': 'Başlık boş olamaz.',
  'error.not_found': 'Kayıt bulunamadı.',
  'error.already_done': 'İş emri zaten tamamlandı.',
  'error.not_blocked': 'İş emri engellenmiş durumda değil.',
  'error.not_ready': 'Aşama henüz başlatılamaz.',
  'error.unknown_role': 'Bilinmeyen rol.',
  'error.no_binding': 'Bu rol için hesap bağlantısı yok.',
  'error.no_account': 'Kullanılabilir hesap yok.',
  'error.not_current_stage': 'Kapı geçerli aşamanın kapısı değil.',
  'error.not_pending': 'Kapı onay bekliyor durumda değil.',
  'error.not_a_human_gate': 'Bu kapı insan kararıyla açılmaz.',
  'error.agent_cannot_decide': 'Bu kararı yalnızca insan verebilir.',
  'error.stale': 'Teklif güncel değil; önce değişikliği yenileyin.',
  'error.self_approval': 'Kendi teklifinizi onaylayamazsınız.',
  'error.invalid_after': 'Teklifin geçerlilik zamanı geçersiz.',
  'error.binding_exists': 'Hesap bir rol bağlantısında kullanılıyor; önce bağlantıyı güncelleyin.',
  'error.not_a_deploy_gate': 'Bu kapı bir dağıtım kapısı değil.',
  'error.no_approval': 'Dağıtımı yalnızca kullanıcı onaylayabilir.',
  'error.confirmation_mismatch': 'Ortam adı doğrulaması eşleşmiyor; ortam adını aynen yazın.',
  'error.promote_prerequisite_missing': 'Aynı işlenen önce önceki ortamda başarıyla dağıtılmalı.',
  'error.unknown_environment': 'Ortam tanımları arasında bulunamadı.',
  'error.no_repo': 'Depo çalışma kopyası hazırlanamadı.',
  'error.unknown': 'Beklenmeyen bir hata oluştu.',
  'attention.permission_ask': 'İzin bekleniyor',
  'attention.awaiting_human': 'İnsan yanıtı bekleniyor',
  'attention.limit_waiting': 'Limit bekleniyor',
  'attention.blocked': 'Engellendi',
  'validate.title_required': 'Bir başlık yazın.',
  'validate.flow_required': 'Bir akış seçin.',
  'gate.state.pending': 'Bekliyor',
  'gate.state.passed': 'Geçti',
  'gate.state.upcoming': 'Sırada',
  'gate.deploy.protected': 'Korumalı ortam',
  'gate.deploy.prerequisite': 'Yükseltme zinciri',
  'wo.status.ready': 'Hazır',
  'wo.status.running': 'Koşuyor',
  'wo.status.gating': 'Değerlendiriliyor',
  'wo.status.awaiting_human': 'İnsan yanıtı bekleniyor',
  'wo.status.limit_waiting': 'Limit bekleniyor',
  'wo.status.blocked': 'Engellendi',
  'wo.status.done': 'Tamamlandı',
  'detail.section.stages': 'Aşamalar ve kapılar',
  'detail.section.runs': 'Koşular',
  'detail.section.environments': 'Ortamlar',
  'detail.section.asks': 'İzin soruları',
  'detail.stage.current': 'Şu anki aşama',
  'detail.action.startStage': 'Aşamayı başlat',
  'detail.loading': 'Yükleniyor…',
  'detail.run.empty': 'Bu iş emrinde henüz koşu yok.',
  'detail.run.running': 'Koşuyor',
  'run.outcome.succeeded': 'Başarılı',
  'run.outcome.failed': 'Başarısız',
  'run.outcome.limit': 'Limit',
  'run.outcome.cancelled': 'İptal edildi',
  'gate.kind.human': 'İnsan onayı',
  'gate.kind.command': 'Komut takımı',
  'gate.kind.agent_verdict': 'Ajan kararı',
  'gate.kind.secret_scan': 'Sır taraması',
  'gate.kind.page_approval': 'Sayfa onayı',
  'gate.kind.deploy': 'Dağıtım',
  'gate.kind.remote_checks': 'Uzak kontroller',
  'action.approve': 'Onayla',
  'action.reject': 'Reddet',
  'action.allow': 'İzin ver',
  'action.deny': 'Reddet',
  'detail.deploy.commitLabel': 'İşlenen (commit)',
  'detail.deploy.commitPlaceholder': 'dağıtılacak işlenen kimliği',
  'detail.deploy.confirmPrompt': 'Korumalı ortam: onaylamak için ortam adını aynen yazın.',
  'detail.deploy.confirmPlaceholder': 'ortam adı',
  'detail.deploy.approve': 'Dağıtımı onayla',
  'detail.secretScan.pending': 'Tarama bekliyor: değişiklikler yerelde sır desenlerine karşı taranacak.',
  'detail.secretScan.passed': 'Tarama bulgu vermedi: değişikliklerde sır deseni bulunamadı.',
  'live.title': 'Canlı akış',
  'live.empty': 'Olay bekleniyor…',
  'live.ended': 'Akış bitti.',
  'live.ask.title': 'İzin sorusu',
  'live.kind.thought': 'Düşünce',
  'live.kind.message': 'İleti',
  'live.kind.usage': 'Kullanım',
  'live.kind.quotaSignal': 'Kota sinyali',
  'live.tool.running': 'çalışıyor',
  'live.tool.ok': 'tamam',
  'live.tool.failed': 'başarısız',
  'live.usage.input': 'girdi',
  'live.usage.output': 'çıktı',
  'live.usage.cached': 'önbellek',
  'live.usage.cost': 'maliyet',
  'live.meter.used': 'kullanılan',
  'live.meter.limit': 'limit',
  'shell.title': 'Docket',
  'nav.cockpit': 'Kokpit',
  'nav.workspaces': 'Repolar',
  'nav.workspaces.empty': 'Henüz repo yok.',
  'cockpit.section.attention': 'Senden bekleyenler',
  'cockpit.section.running': 'Koşanlar',
  'cockpit.attention.empty': 'Şu an senden bekleyen yok.',
  'cockpit.running.empty': 'Şu an koşan yok.',
  'cockpit.loading': 'Yükleniyor…',
  'board.loading': 'Yükleniyor…',
  'board.section.done': 'Tamamlananlar',
  'board.create.title': 'Yeni iş emri',
  'board.create.titleLabel': 'Başlık',
  'board.create.titlePlaceholder': 'iş emri başlığı',
  'board.create.flowLabel': 'Akış',
  'board.create.flowPlaceholder': 'akış',
  'board.create.submit': 'Aç',
  'action.retry': 'Yeniden dene',
  'action.open': 'Aç',
  'success.workOrder.open': 'İş emri açıldı.',
  'success.workOrder.block': 'İş emri engellendi.',
  'success.workOrder.unblock': 'İş emrinin engeli kaldırıldı.',
  'success.workOrder.close': 'İş emri kapatıldı.',
  'success.workOrder.enqueue': 'Aşama kuyruğa alındı.',
  'success.task.open': 'Görevün iş emirleri açıldı.',
  'success.project.attach': 'Proje eklendi.',
  'success.repo.register': 'Depo kaydı yapıldı.',
  'success.repo.unregister': 'Depo kaydı kaldırıldı.',
  'success.gate.decide': 'Kapı kararı kaydedildi.',
  'success.proposal.decide': 'Teklif kararı kaydedildi.',
  'success.permission.answer': 'İzin yanıtı kaydedildi.',
  'success.deploy.approve': 'Dağıtım onaylandı ve çalıştırıldı.',
  'nav.settings': 'Ayarlar',
  'settings.section.accounts': 'Hesaplar',
  'settings.section.bindings': 'Rol bağlantıları',
  'settings.section.discovery': 'Sağlayıcı keşfi',
  'settings.accounts.empty': 'Henüz hesap yok.',
  'settings.meters.empty': 'Bu hesap için ölçüm yok.',
  'settings.meter.remaining': 'kalan',
  'settings.meter.resetsAt': 'yenilenme',
  'settings.account.remove': 'Hesabı kaldır',
  'settings.remove.warning': 'Bu hesap şu rol bağlantılarında kullanılıyor:',
  'settings.remove.confirm': 'Yine de kaldır',
  'settings.remove.cancel': 'Vazgeç',
  'settings.binding.edit': 'Düzenle',
  'settings.binding.save': 'Kaydet',
  'settings.binding.cancel': 'Vazgeç',
  'settings.binding.add': 'Yeni bağlantı',
  'settings.binding.empty': 'Henüz rol bağlantısı yok.',
  'settings.binding.role': 'Rol',
  'settings.binding.rolePlaceholder': 'rol (slug)',
  'settings.binding.model': 'model',
  'settings.binding.scope.global': 'Tüm makine',
  'settings.binding.scope.workspace': 'Repo',
  'settings.binding.scope.project': 'Proje',
  'settings.binding.scope.workOrder': 'İş emri',
  'settings.discovery.refresh': 'Keşfet',
  'settings.discovery.running': 'Keşif koşuyor…',
  'settings.discovery.failed': 'Keşif başarısız oldu.',
  'settings.discovery.empty': 'Henüz keşif sonucu yok.',
  'settings.discovery.flags': 'bayraklar',
  'settings.language.label': 'Dil',
  'settings.language.tr': 'Türkçe',
  'settings.language.en': 'English',
  'source.pushed': 'gönderildi',
  'source.polled': 'sorgulandı',
  'source.header': 'başlık',
  'source.captured_from_error': 'hatadan yakalandı',
  'source.estimated': 'tahmini',
  'source.documented_rule': 'belgelenmiş kural',
  'source.unknown': 'bilinmiyor',
  'auth.mode.subscription': 'Abonelik',
  'auth.mode.api_key': 'API anahtarı',
  'auth.mode.cloud': 'Bulut',
  'auth.mode.byok': 'Kendi anahtarın',
  'wizard.title': 'Kurulum',
  'wizard.checking': 'Kontrol ediliyor…',
  'wizard.step.source': 'Tanım kaynağı',
  'wizard.step.account': 'Hesap',
  'wizard.step.binding': 'Rol bağlantısı',
  'wizard.step.done': 'Tamamlandı',
  'wizard.back': 'Geri',
  'wizard.next': 'Devam',
  'wizard.hint.source': 'Devam etmek için tanım kaynağını doğrulayın.',
  'wizard.hint.account': 'Devam etmek için kurulu ve giriş yapılmış bir sağlayıcı seçin.',
  'wizard.hint.binding': 'Devam etmek için en az bir rol bağlayın.',
  'wizard.source.label': 'Tanım kaynağı',
  'wizard.source.placeholder': 'repo (slug)',
  'wizard.source.check': 'Kaynağı doğrula',
  'wizard.source.probing': 'Doğrulanıyor…',
  'wizard.source.ok': 'Kaynak okunuyor.',
  'wizard.source.failed': 'Kaynak okunamadı.',
  'wizard.account.title': 'Bulunan sağlayıcılar',
  'wizard.account.refresh': 'Yeniden tara',
  'wizard.account.empty': 'Kurulu sağlayıcı bulunamadı.',
  'wizard.account.selected': 'Seçildi',
  'wizard.account.label': 'Hesap adı',
  'wizard.account.labelPlaceholder': 'hesap adı',
  'wizard.account.authMode': 'Kimlik doğrulama',
  'wizard.account.plan': 'Plan (isteğe bağlı)',
  'wizard.account.planPlaceholder': 'plan',
  'wizard.binding.role': 'Rol',
  'wizard.binding.rolePlaceholder': 'rol (slug)',
  'wizard.binding.bind': 'Rolü bağla',
  'wizard.binding.bound': 'Bağlı roller',
  'wizard.binding.empty': 'Henüz rol bağlanmadı.',
  'discovery.found': 'bulundu',
  'discovery.missing': 'bulunamadı',
  'discovery.loggedIn': 'giriş yapılmış',
  'discovery.loginRequired': 'giriş gerekli',
  'discovery.loginUnknown': 'giriş durumu bilinmiyor',
  'errorBoundary.title': 'Uygulama beklenmeyen bir hatayla karşılaşt.',
  'errorBoundary.reload': 'Yeniden yükle',
  'success.account.save': 'Hesap kaydedildi.',
  'success.account.remove': 'Hesap kaldırıldı.',
  'success.binding.save': 'Rol bağlantısı kaydedildi.',
};
