// labels/tr.ts — Turkish bundle. Turkish is the default locale; every key of keys.ts carries copy.
import type { LabelBundle } from './keys';

export const TR: LabelBundle = {
  'error.invalid_id': 'Geçersiz kimlik.',
  'error.definitions_invalid': 'Tanımlar geçersiz; çalışma alanı tanımı okunamadı.',
  'error.unknown_flow': 'Bilinmeyen akış.',
  'error.flow_not_enabled': 'Bu akış çalışma alanında etkin değil.',
  'error.unknown_task': 'Bilinmeyen görev.',
  'error.empty_title': 'Başlık boş olamaz.',
  'error.not_found': 'Kayıt bulunamadı.',
  'error.already_done': 'İş emri zaten tamamlandı.',
  'error.not_blocked': 'İş emri engellenmiş durumda değil.',
  'error.not_ready': 'Aşama henüz başlatılamaz.',
  'error.unknown_role': 'Bilinmeyen rol.',
  'error.no_binding': 'Bu rol için hesap bağlantısı yok.',
  'error.no_account': 'Kullanılabilir hesap yok.',
  'error.not_current_stage': 'Kapı geçerli aşamanın kapısı değil.',
  'error.not_pending': 'Kapı onay bekliyor durumda değil.',
  'error.not_a_human_gate': 'Bu kapı insan kararıyla açılmaz.',
  'error.agent_cannot_decide': 'Bu kararı yalnızca insan verebilir.',
  'error.stale': 'Teklif güncel değil; önce değişikliği yenileyin.',
  'error.self_approval': 'Kendi teklifinizi onaylayamazsınız.',
  'error.invalid_after': 'Teklifin geçerlilik zamanı geçersiz.',
  'error.not_a_deploy_gate': 'Bu kapı bir dağıtım kapısı değil.',
  'error.no_approval': 'Dağıtımı yalnızca kullanıcı onaylayabilir.',
  'error.confirmation_mismatch': 'Ortam adı doğrulaması eşleşmiyor; ortam adını aynen yazın.',
  'error.promote_prerequisite_missing': 'Aynı işlenen önce önceki ortamda başarıyla dağıtılmalı.',
  'error.unknown_environment': 'Ortam tanımları arasında bulunamadı.',
  'error.no_repo': 'Depo çalışma kopyası hazırlanamadı.',
  'error.unknown': 'Beklenmeyen bir hata oluştu.',
  'attention.permission_ask': 'İzin bekleniyor',
  'attention.awaiting_human': 'İnsan yanıtı bekleniyor',
  'attention.limit_waiting': 'Limit bekleniyor',
  'attention.blocked': 'Engellendi',
  'validate.title_required': 'Bir başlık yazın.',
  'validate.flow_required': 'Bir akış seçin.',
  'gate.state.pending': 'Bekliyor',
  'gate.state.passed': 'Geçti',
  'gate.state.upcoming': 'Sırada',
  'gate.deploy.protected': 'Korumalı ortam',
  'gate.deploy.prerequisite': 'Yükseltme zinciri',
  'success.workOrder.open': 'İş emri açıldı.',
  'success.workOrder.block': 'İş emri engellendi.',
  'success.workOrder.unblock': 'İş emrinin engeli kaldırıldı.',
  'success.workOrder.close': 'İş emri kapatıldı.',
  'success.workOrder.enqueue': 'Aşama kuyruğa alındı.',
  'success.gate.decide': 'Kapı kararı kaydedildi.',
  'success.proposal.decide': 'Teklif kararı kaydedildi.',
  'success.permission.answer': 'İzin yanıtı kaydedildi.',
  'success.deploy.approve': 'Dağıtım onaylandı ve çalıştırıldı.',
};
