// The built-in provider set: pure data plus one pure buildLaunch per CLI, written from each
// CLI's own public documentation. Flag-level accuracy is operator-verified data — a wrong flag
// here is a data fix, never a contract change.
import type { ProviderDef } from './provider-def';

export const BUILTIN_PROVIDER_DEFS: readonly ProviderDef[] = [
  {
    id: 'claude-code',
    displayName: 'Claude Code',
    bins: ['claude'],
    versionArgs: ['--version'],
    helpArgs: ['--help'],
    transport: 'sdk',
    config: { mechanism: 'env-var', name: 'CLAUDE_CONFIG_DIR' },
    buildLaunch: (input) => ({ args: [], env: { CLAUDE_CONFIG_DIR: input.configDir }, stdin: 'prompt' }),
    resume: 'specify',
    capabilities: {
      structuredStream: true,
      permissionAsk: true,
      resume: true,
      mcp: true,
      hooks: true,
      skills: true,
      images: true,
      quotaReport: 'stream',
      costReport: 'reported',
    },
    installHint: { url: 'https://docs.anthropic.com/en/docs/claude-code' },
  },
  {
    id: 'codex',
    displayName: 'Codex',
    bins: ['codex'],
    versionArgs: ['--version'],
    helpArgs: ['--help'],
    authProbe: { args: ['login', 'status'] },
    transport: 'app-server',
    config: { mechanism: 'env-var', name: 'CODEX_HOME' },
    buildLaunch: (input) => ({ args: ['app-server'], env: { CODEX_HOME: input.configDir }, stdin: 'prompt' }),
    resume: 'protocol',
    capabilities: {
      structuredStream: true,
      permissionAsk: true,
      resume: true,
      mcp: true,
      hooks: 'unknown',
      skills: 'unknown',
      images: true,
      quotaReport: 'query',
      costReport: 'none',
    },
    installHint: { url: 'https://developers.openai.com/codex/cli' },
  },
  {
    id: 'agy',
    displayName: 'Antigravity',
    bins: ['agy'],
    versionArgs: ['--version'],
    helpArgs: ['--help'],
    transport: 'stream-json',
    streamDialect: 'agy',
    // This CLI documents no config-dir override of its own; the run-scoped HOME carries the
    // run directory until a dedicated variable exists.
    config: { mechanism: 'env-var', name: 'HOME' },
    buildLaunch: (input) => ({
      args: ['--input-format', 'stream-json', '--output-format', 'stream-json'],
      env: { HOME: input.configDir },
      stdin: 'prompt',
    }),
    resume: 'specify',
    capabilities: {
      structuredStream: true,
      permissionAsk: false,
      resume: true,
      mcp: 'unknown',
      hooks: 'unknown',
      skills: 'unknown',
      images: 'unknown',
      quotaReport: 'query',
      costReport: 'none',
    },
    installHint: { url: 'https://antigravity.google/docs/cli' },
  },
  {
    id: 'gemini',
    displayName: 'Gemini CLI',
    bins: ['gemini'],
    versionArgs: ['--version'],
    helpArgs: ['--help'],
    transport: 'acp',
    config: { mechanism: 'env-var', name: 'GEMINI_CLI_HOME' },
    buildLaunch: (input) => ({ args: ['--experimental-acp'], env: { GEMINI_CLI_HOME: input.configDir }, stdin: 'prompt' }),
    resume: 'protocol',
    capabilities: {
      structuredStream: true,
      permissionAsk: 'unknown',
      resume: true,
      mcp: true,
      hooks: 'unknown',
      skills: 'unknown',
      images: true,
      quotaReport: 'none',
      costReport: 'none',
    },
    installHint: { url: 'https://google-gemini.github.io/gemini-cli/' },
  },
  {
    id: 'copilot',
    displayName: 'Copilot CLI',
    bins: ['copilot'],
    versionArgs: ['--version'],
    helpArgs: ['--help'],
    transport: 'acp',
    // No dedicated config-dir variable is documented; the run-scoped HOME isolates the config tree.
    config: { mechanism: 'env-var', name: 'HOME' },
    buildLaunch: (input) => ({ args: ['--acp', '--stdio'], env: { HOME: input.configDir }, stdin: 'prompt' }),
    resume: 'protocol',
    capabilities: {
      structuredStream: true,
      // probe #139: asks and blocks out-of-cwd; in-cwd edits auto-allowed (copilot asks for those too).
      permissionAsk: true,
      resume: true,
      mcp: true,
      hooks: 'unknown',
      skills: 'unknown',
      images: true,
      quotaReport: 'none',
      costReport: 'none',
    },
    installHint: { url: 'https://docs.github.com/en/copilot/reference/copilot-cli-reference' },
  },
  {
    id: 'cursor',
    displayName: 'Cursor Agent',
    bins: ['cursor-agent'],
    versionArgs: ['--version'],
    helpArgs: ['--help'],
    transport: 'acp',
    // No dedicated config-dir variable is documented; the run-scoped HOME isolates the config tree.
    config: { mechanism: 'env-var', name: 'HOME' },
    buildLaunch: (input) => ({ args: ['acp'], env: { HOME: input.configDir }, stdin: 'prompt' }),
    resume: 'protocol',
    capabilities: {
      structuredStream: true,
      // probe #139: asks and blocks out-of-cwd; in-cwd edits auto-allowed (copilot asks for those too).
      permissionAsk: true,
      resume: true,
      mcp: true,
      hooks: 'unknown',
      skills: 'unknown',
      images: true,
      quotaReport: 'none',
      costReport: 'none',
    },
    installHint: { url: 'https://cursor.com/docs/cli' },
  },
  {
    id: 'opencode',
    displayName: 'opencode',
    bins: ['opencode'],
    versionArgs: ['--version'],
    helpArgs: ['--help'],
    transport: 'acp',
    config: { mechanism: 'env-var', name: 'OPENCODE_CONFIG_DIR' },
    buildLaunch: (input) => ({ args: ['acp'], env: { OPENCODE_CONFIG_DIR: input.configDir }, stdin: 'prompt' }),
    resume: 'protocol',
    capabilities: {
      structuredStream: true,
      // probe #139: asks and blocks out-of-cwd; in-cwd edits auto-allowed (copilot asks for those too).
      permissionAsk: true,
      resume: true,
      mcp: true,
      hooks: 'unknown',
      skills: 'unknown',
      images: true,
      quotaReport: 'none',
      costReport: 'none',
    },
    installHint: { url: 'https://opencode.ai/docs' },
  },
];
